### ISSUE TITLE
Time for double IP after watching a video is wrong

### ISSUE THREAD

**Issue by Dashie97** [antimatter-dimensions/mobile-issues#11]
**Describe the bug**
The time where IP gain is multiplied by 2 is set back to 4 hours instead of increasing the timer by 4 hours. This can obviously just be observed if the timer is actually running.

**To Reproduce**
1. Go shop
2. Click the button for doubled IP gain by watching a video
3. Watch the video and provide Hevi with some sweet $$$
4. Observe the timer as it runs down from 4 hours
5. Click the timer again and watch the video
6. The timer is set back to 4 hours instead of adding 4 hours to the timer

**Expected behavior**
Add 4 hours to the timer for every video watched

**Comment by kajfik** [comment]
This behavior is intended, but I will ask Hevi what he thinks about this.

**Comment by kajfik** [comment]
Hevi's comment: I think the behavior should be like that, but perhaps add a text when the timer is on that rewatching refreshes the timer.

**Comment by kajfik** [comment]
Fixed in 2.6.0
