### ISSUE TITLE
Show eternity count on milestone page

### ISSUE THREAD

**Issue by earthernsence** [antimatter-dimensions/mobile-issues#111]
**Is your feature request related to a problem? Please describe.**
You can't see the amount of eternities you have on the milestone page like you can in the reality update.

**Describe the solution you'd like**
A header on the milestone page showing the amount of eternities you have.

**Describe alternatives you've considered**
I haven't given much thought into alternatives, but I'm sure you can think of some.

**Comment by kajfik** [comment]
Added in 2.12.1
