### ISSUE TITLE
Change ip generator text

### ISSUE THREAD

**Issue by HyperCrafting** [antimatter-dimensions/mobile-issues#117]
Too many people not understanding "based on"

Change the text from "Infinity Point generation based on fastest infinity" to 
"Infinity Point generation based on fastest infinity time x10" 
Or
"Passively generate Infinity Points 10 times slower than your fastest infinity"

**Comment by kajfik** [comment]
Changed to "Passively generate Infinity Points 10 times slower than your fastest Infinity" in 2.12.1.
