### ISSUE TITLE
Add an option to disable fullscreen

### ISSUE THREAD

**Issue by kajfik** [antimatter-dimensions/mobile-issues#124]
**Is your feature request related to a problem? Please describe.**
Should help Android 10 devices use the bottom gestures.

**Comment by OvermindDL1** [comment]
Just be warned, if full screen is disabled on Windows 10 gestures then we can't swipe in from the edges without hitting the Back gesture unless you define some side bounds or something first.  I haven't looked at the API docs in detail yet, only a quick skimming, but so far staying in fullscreen mode is just fine in Android 10, just means that I have to swipe up first and then I can use the gestures.

It would be nice to define the side bounds or whatever it was though, that way the application won't quit if I swipe in from the side twice too fast.  😅

**Comment by kajfik** [comment]
Added in 2.12.2 as a "Bottom bar" option.
