### ISSUE TITLE
Export to web is bugged with the Mixed logarithm notation.

### ISSUE THREAD

**Issue by kajfik** [antimatter-dimensions/mobile-issues#133]
Reddit thread: https://www.reddit.com/r/AntimatterDimensions/comments/e3kdkp/mobile_export_to_web_bug/
Bugged save from the thread: https://ghostbin.co/paste/4t3te

**Comment by ioanniskatagas** [comment]
Currently trying to export to web and failing to import the save.

I think the problem is not the notation, I always use scientific (not working) and also tried with standard (also not working).

**Comment by kajfik** [comment]
@ioanniskatagas Could you please share your save via pastebin? Thanks a lot.

**Comment by ioanniskatagas** [comment]
@kajfik000 https://pastebin.com/8yJSVSFj

**Comment by kajfik** [comment]
@ioanniskatagas Your save is cut (it has exactly 5000 characters). This may be caused by sending the save to your pc via some messaging services like messenger or whatsapp or by the limitations of your device's clipboard. What service did you use to send the save to your pc? I recommend trying email/pastebin/google doc.

**Comment by ioanniskatagas** [comment]
@kajfik000 Ah, you are right, solved my issue. 
And as i can see the mixed log is kind of bugged/hacked, the rest is working (for me at least).

**Comment by kajfik** [comment]
Fixed in 2.14.11
