### ISSUE TITLE
Default notation change to Standard

### ISSUE THREAD

**Issue by F1e308** [antimatter-dimensions/mobile-issues#136]
In PC,when you start the game,notation will turn to standard first.

**Comment by kajfik** [comment]
That's incorrect, the default notation on both web and mobile is "Mixed scientific".

Thanks for letting me know, the default notation will be fixed in 2.14.12.

**Comment by F1e308** [comment]
But PC start is standard.
Link:
http://www.ivark.github.io

在 2019年12月4日週三 04:36，kajfik000 <notifications@github.com> 寫道：

**Comment by F1e308** [comment]
www.ivark.github.io

在 2019年12月4日週三 04:36，kajfik000 <notifications@github.com> 寫道：
