### ISSUE TITLE
Add option for top bar when use currency amount

### ISSUE THREAD

**Issue by F1e308** [antimatter-dimensions/mobile-issues#140]
You can use 1 or 2 of this:
Antimatter
Infinity Point(need infinity once)
Time Theorem(need eternity once)
Eternity Point(need eternity once)
Tachyon Particle(need unlock dilation)
Dilated Time(need unlock dilation)

Current:
Antimatter(pre infinity)
Infinity Point+Antimatter(post infinity)
Eternity Point+Time Theorem(post eternity)
Tachyon Particle+Dilated Time(post dilation)

**Comment by kajfik** [comment]
Please use the #suggestions or #mobile channels on the Discord server for suggestions, thanks.

**Comment by F1e308** [comment]
Banned

在 2019年12月7日週六 17:10，kajfik000 <notifications@github.com> 寫道：
