### ISSUE TITLE
Change galaxy display

### ISSUE THREAD

**Issue by kajfik** [antimatter-dimensions/mobile-issues#147]
**Is your feature request related to a problem? Please describe.**
The Galaxy text (Far Galaxies (809+360+124)) is too long when translated and doesn't fit on one line.

**Describe the solution you'd like**
Change the galaxy amounts to their sum, so for example (1293) instead of (809+360+124).
This will let us use translated terms and also Distant/Remote Galaxies instead of Far Galaxies.

**Screenshot of the old system:**
![](https://cdn.discordapp.com/attachments/351476683016241166/654613587687636992/IMG_20191212_101946.jpg)

**Comment by kajfik** [comment]
**New system:**
![](https://cdn.discordapp.com/attachments/554713718282256391/654694071897554954/IMG_20191212_154019.jpg)

**Comment by kajfik** [comment]
Implemented in 2.14.14i2

**Comment by OvermindDL1** [comment]
Is there any way to keep the `+` versions, being able to see what it is built up from is a huge help with certain things.  Or perhaps even a `...+...+...=...` version?

**Comment by kajfik** [comment]
@OvermindDL1 The web Reality update will use the `...+...+...=...` version.

We need to make some compromises on mobile: first we decided to use "Far" which is a shorter word that fits on one line together with the (++) display, but now that we are alpha-testing translations we had a problem where some languages don't have a short word like "Far" so the text was split to two lines which looked really bad.

You can still see the amount galaxies you get from Replicantis and Dilation in their respective tabs.

**Comment by kajfik** [comment]
Although right now the mobile testers have informed me that with this new system you can't know how many galaxies to cap when farming infinities for example. I will think about adding an option to switch between the two versions.

**Comment by kajfik** [comment]
There is also an option to make the `...+...+...=...` version appear in a popup when you click on the galaxy amount.

**Comment by OvermindDL1** [comment]
> You can still see the amount galaxies you get from Replicantis and Dilation in their respective tabs.

That then means having to do math to calculate how many normal galaxies you have though, which is important at times.

I'd definitely prefer to have the `...+...+...=...` on the button itself, at least on my phone there is plenty of room on the button, and I wouldn't mind another line added at all (there is sooooo much empty space at the bottom of that screen).

**Comment by kajfik** [comment]
![](https://cdn.discordapp.com/attachments/554713718282256391/656098908849569792/IMG_20191216_124240.jpg)

**Comment by kajfik** [comment]
Implemented in 2.14.14i4
