### ISSUE TITLE
Side menu is not expanded with "Side menu expanded" option enabled.

### ISSUE THREAD

**Issue by kajfik** [antimatter-dimensions/mobile-issues#162]
**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Perform a Complete reset or load a pre-eternity save
2. Make sure the "Side menu expanded" option is ON
3. Import a post-eternity save
4. The "Eternity" tab in the Side menu is not expanded

**Screenshots**
![](https://cdn.discordapp.com/attachments/634770539998871563/667058822464012290/Screenshot_20200115-113324.jpg)

**Comment by OvermindDL1** [comment]
I've noticed this happen on occasion as well, it's odd...

**Comment by kajfik** [comment]
Fixed in 2.16.3i1
