### ISSUE TITLE
EC numbers and "5" in blind notation

### ISSUE THREAD

**Issue by e4494s** [antimatter-dimensions/mobile-issues#233]
![Screenshot_20200504-120939](https://user-images.githubusercontent.com/61923287/80994139-e4070c00-8e01-11ea-84a7-bfb576b522ce.png)

**Comment by kajfik** [comment]
We are still not sure about formatting the challenge/dimension numbers so I will leave those for now.

**Comment by kajfik** [comment]
Fixed in 2.24.0i1
