### ISSUE TITLE
Have replicanti galaxies bought by Max all

### ISSUE THREAD

**Issue by Cryonic7** [antimatter-dimensions/mobile-issues#244]
**Is your feature request related to a problem? Please describe.**
Playing on active time study tree I have to hold the replicanti button and max all button simultaneously

**Describe the solution you'd like**
An option to have replicanti galaxies bought by Max all. 

**Describe alternatives you've considered**
An upgrade that would add replicanti galaxies to the max all selector and would then apply after getting it

**Comment by kajfik** [comment]
Could you please explain why do you need to hold Max instead of using Dimension and Tickspeed autobuyers?

**Comment by Cryonic7** [comment]
It ends up being faster during short infinities and short eternities when
using the Active Time study tree to hold Max all while doing so as well.
It'd be nice to have RG bought by Max at the same time. A truer max all, if
you will

**Comment by kajfik** [comment]
Max should not be faster than dimension/tickspeed autobuyers. I will solve this by making those autobuyers disabled when Max is held. (Both Max and autobuyers buy in 50ms intervals so if timed well they can buy in 25ms intervals together.)

**Comment by kajfik** [comment]
Fixed in 2.24.0i1 by disabling dim/tickspeed autobuyers when holding Max which makes Max as fast as autobuyers.

**Comment by Cryonic7** [comment]
Why wouldn't max be faster, if it's buying the maximum of each? This seems
like a step in the reverse direction

**Comment by kajfik** [comment]
Max should not be faster than fully upgraded dimensions/tickspeed autobuyers, it should be exactly as fast as them.

**Comment by Cryonic7** [comment]
Well, if max is being changed to only be as fast as autobuyers, could max
also have new functionality to buy replicanti galaxies when held, then? For
use when on active TS tree

**Comment by kajfik** [comment]
No.

**Comment by kajfik** [comment]
If you want to buy RGs via a bottom button you can use the R bottom button (can be enabled in Options by setting the "Bottom buttons" option to "ALL").
