### ISSUE TITLE
Unable to get "A sound financial decision" achievement

### ISSUE THREAD

**Issue by TheCasualObserver** [antimatter-dimensions/mobile-issues#273]
**Describe the bug**
Without a Google-Account it is impossible to get the achievement "A sound financial decision".
I downloaded AD 2.25.0 by using the app "Aurora Store" from F-Droid.
The Button "Buy more" (that is used to get the achievement "A sound financial decision") is grayed-out and I am unable to click on it. See the attached screenshot.

**To Reproduce**
1. Download Antimatter Dimensions via Aurora Store
2. Start the game and click on Menu-Button -> Store
3. Now the button "Buy more" is grayed out.

**Expected behavior**
I would like to be able to get the achievement "A sound financial decision" without the need for a Google-Account.
Clicking the button even when it is grayed-out should award the achievement.

**Screenshots**
![Screenshot_Store](https://user-images.githubusercontent.com/13132706/87196491-50b6ef00-c2fa-11ea-9bda-ad842c8cad08.png)

**Additional context**
Link to Aurora Store: https://f-droid.org/en/packages/com.aurora.store/

**Comment by kajfik** [comment]
Fixed in 2.25.2i1

**Comment by TheCasualObserver** [comment]
Thank you for resolving this issue. I can confirm that in version 2.26.1 I no longer have this problem.
