### ISSUE TITLE
number time studies 

### ISSUE THREAD

**Issue by ARoundCircle** [antimatter-dimensions/mobile-issues#33]
it would be nice if the time studies were numbered so newbies like me will know what ppl r talking about when they say time study xyz, just found out, and so ppl who arent familiar with it wont hv to keep counting from the top

**Comment by kajfik** [comment]
Time study number can be enabled in Options - UI - Time study numbers.

**Comment by ARoundCircle** [comment]
yeo i found out afterwards so i closed it. thanks
