### ISSUE TITLE
Bottom buttons

### ISSUE THREAD

**Issue by SsNiPeR1** [antimatter-dimensions/mobile-issues#372]
**Is your feature request related to a problem? Please describe.**
So, before the update i had only one Max button. Now I have 6 buttons, like eternity dimboost etc.

**Describe the solution you'd like**
A setting in settings that allows not to show all the buttons but only needed

**Describe alternatives you've considered**
Install older version

**Additional context**
![Screenshot_2021-11-08-14-47-14-823_kajfosz.antimatterdimensions.jpg](https://user-images.githubusercontent.com/63201833/140737305-a2f8c927-9168-43d0-b325-92af69edea1e.jpg)

**Comment by SsNiPeR1** [comment]
Solved now.

**Comment by demndevel** [comment]
> Solved now.

:redebalo:
