### ISSUE TITLE
BH stays inverted upon entering cel7

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#409]
**Describe the bug**
BH stays inverted upon entering cel7.

**To Reproduce**
1. Load save
2. Invert BH (best to see with fully inverted BH)
3. Enter cel7
4. See poopoo (try to buy dims)

**Expected behavior**
BH should resume upon entering cel7.

**Savefile**
https://paste.ee/p/09zjq

**Additional context**
For now there's the option to un-invert the BH while in cel7 because slider stays visible and accessable, but [see next issue/suggestion I'll make in a sec].

**Comment by kajfik** [comment]
Fixed in 2.111.0i6
