### ISSUE TITLE
BH tab UI in cel7 and cel2

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#410]
**Is your feature request related to a problem? Please describe.**
In cel2 and cel7, slider for inverting the BH stylus visible and accessable and can actually affect BH inverting in cel7. On top of that I have a button to unleash the BH while in cel7.

**Describe the solution you'd like**
Since there are no BHs in either of those celestials allowed, the slider should not be shown. Same goes for pulse and pause button.
There shouldn't be the unleash BH button in cel7.

**Describe alternatives you've considered**
I have not thought about alternatives.

**Additional context**
Save file (before entering doomed so you can check cel3)
https://paste.ee/p/09zjq

**Comment by kajfik** [comment]
Implemented in 2.111.0i6
