### ISSUE TITLE
Glyph undo

### ISSUE THREAD

**Issue by kajfik** [antimatter-dimensions/mobile-issues#420]

**Comment by KirinNijinski** [comment]
Is glyph undo not implemented yet ? Because it doesn't work at all. The button is there, but never become clickable, even when the glyph is equiped in the same reality

**Comment by kajfik** [comment]
Yes, this is exactly why this issue exists.

**Comment by KirinNijinski** [comment]
Oh ok. Sorry, I don't use github often. (I didn't distinguish bug/feature tag)

**Comment by kajfik** [comment]
Added in 2.111.0i28
