### ISSUE TITLE
Next *pair* of Tachyon Galaxies still appears when beyond 1000 TG

### ISSUE THREAD

**Issue by danikwk** [antimatter-dimensions/mobile-issues#488]
![Screenshot_20230217-104220](https://user-images.githubusercontent.com/123486353/219700848-bb608074-68e2-4b44-924c-b0fac3c3f831.png)

Should not have "pair," as you only get single TG past 1000 total TG or 500 base.

**Comment by kajfik** [comment]
Fixed in 2.111.0i10
