### ISSUE TITLE
EC6 and EC12's "Next:" reward text gets cut off in portrait

### ISSUE THREAD

**Issue by L5racer** [antimatter-dimensions/mobile-issues#489]
![Screenshot_20230216_203331_Antimatter Dimensions](https://user-images.githubusercontent.com/125624914/219783683-4f20a309-3faf-42a1-af8d-4432e859851b.jpg)
![Screenshot_20230217_140800_Antimatter Dimensions](https://user-images.githubusercontent.com/125624914/219783701-7b6d7848-40cd-4835-bb7f-bfc0641d2b5e.jpg)
If these challenges aren't fully completed, the "Next:" text for these challenges is cut off at the bottom. Restarting or switching orientation and back doesn't seem to fix it.
I'm using a Galaxy S22, it may not be an issue with other phones.
If it matters, I started the first completion of them through the study tree and beat them before going to the EC tab.

**Comment by kajfik** [comment]
What is your text size in the Options tab?

**Comment by L5racer** [comment]
> What is your text size in the Options tab?

Didn't see this until now, sorry
It's at 100%
(...accidentally closed and opened this again)

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
