### ISSUE TITLE
The Paradoxical Forever has the wrong formula

### ISSUE THREAD

**Issue by Calmcat5** [antimatter-dimensions/mobile-issues#490]
**Describe the issue**
A clear and concise description of a feature that causes the issue.

The formula for Reality Upgrade "The Paradoxical Forever" appears to scale differently on mobile and web (mobile's is stronger).

**Describe the solution you'd like**

For the formula to be consistent on both platforms. I'm not quite sure which formula is the better one, but they should align.

**Describe alternatives you've considered**

delete the upgrade and never speak about it again

**Additional context**

Web photo taken at over 1e5000 EP, mobile photo taken by The Cube Dude#7897 at 1e3020 EP.
![Screenshot_20230217_150723_Antimatter_Dimensions](https://user-images.githubusercontent.com/94936969/219797351-93471cd0-2e69-4b92-b660-d86342f24825.jpg)
![image](https://user-images.githubusercontent.com/94936969/219797352-24b875e6-e89b-4799-ab63-c344a6ec2029.png)

**Comment by Calmcat5** [comment]
oh right steps to reproduce:
1. get some large ep number
2. do this for mobile and web
3. observe the multiplier
4. (profit?)

**Comment by Calmcat5** [comment]
dammit kaj why you gotta be so fast

**Comment by kajfik** [comment]
Still thanks a lot for finding this
