### ISSUE TITLE
ad bonus stops me from being optimal (crunch&eternity autobuyer)

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#492]
**Describe the bug**
Cannot put a number like 5.11e7 into "after ad bonus" crunch buyer because after ad bonus = 2x of non-ad bonus variable. And since crunch buyer only allows for two digits-number formats, it gets rounded up down, so the after ad bonus also gets upped.
Nevertheless big crunch buyer shows peak IP/min at 5.11e7, means I cannot be optimal using crunch autobuyer.
Literally unplayable. Dislike, gonna uninstall the game. I want my money back.

**To Reproduce**
1. Invest in ad bonus (honest recommendation for casuals: dont.)
2. Load save/be at a stage where ad bonus affects IP gain
3. Try to put 5el.11e7 into after ad bonus crunch buyer
4. See poopoo, crunch gets set to 5.12e7

**Expected behavior**
Have it be at 5.11e7.
Only (kinda whacky) solution I could though of would maybe be, that we allow three digits in the "before and bonus" crunch buyer. (If player doesn't input three digits, it should only show two tho.) That would allow 2.555e7 before and bonus and 5.11e7 after ad bonus.

**Other solutions I thought of**
Gimme ma money back :babagun:

**Screenshots**
https://discord.com/channels/351476683016241162/554713718282256391/1076473195835699301

**Savefile**
https://paste.ee/p/Jqlhp

**Additional context**
Probably affects eternity buyer too. Haven't tested yet. Will do once I get there in cel7.
Also yeah, ik ad bonus is meant to be disabled in cel7, but that's also pre cel7 issue so

**Comment by kajfik** [comment]
Fixed in 2.111.0i10
