### ISSUE TITLE
Make IP/min disappear on buying 5e11 upgrade, not just reaching it

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#495]
**Is your feature request related to a problem? Please describe.**
People may be stupid. If you reach 5e11 IP and spend it on f.e. ID1 or another IP gen upgrade, you drop below 5e11 IP but the IP/min display on crunch buyer is gone.

**Describe the solution you'd like**
IP/min should be displayed until you purchase the 5e11 galaxy upgrade.

**Describe alternatives you've considered**
No.

**Additional context**
I should make lunch rn but couch is too cosy. :blobcomfy:

**Comment by kajfik** [comment]
Fixed in 2.44.0i1

**Comment by kajfik** [comment]
Hope your lunch was good :blobcomfy:
