### ISSUE TITLE
2nd strike checks for wrong upgrade

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#496]
**Describe the bug**
Decay gets triggered after getting the 1e15 autobuyer speedup, not the 5e11 galaxy upgrade.

**To Reproduce**
1. Load save
2. See no decay in cel7 tab
3. Go to break tab, see 5e11 is bought, buy 1e15
4. See poopoo, decay now there

**Expected behavior**
Check for 5e11 upgrade

**Savefile**
https://paste.ee/p/VuEWM

**Comment by kajfik** [comment]
Fixed in 2.111.0i8
