### ISSUE TITLE
Inf tab forced to shown in cel7 (even after buying all possible upgrades)

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#497]
**Describe the bug**
Cannot hide inf tab after buying all 4 rows of inf upgrades.

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Load save
2. Try to hide inf tab
3. See error

**Expected behavior**
Hide inf tab after buying all 4 rows of inf upgrades.

**Savefile**
https://paste.ee/p/VuEWM

**Additional context**
I assume since you cannot get the 2xIP and the offline gen, the tab still thinks there are upgrades to be bought, but those two are disabled and the tab should be able to get hidden.

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
