### ISSUE TITLE
Inaccurate display of TTs

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#498]
**Describe the bug**
The display for TTs doesn't seem to be correct as I am unable to purchase a Time Study even with the correct number of TTs.

**To Reproduce**
1. Disable offline progress (The bug seems to resolve itself after some time)
2. Import the save
3. Go to the Time Studies tab

**Expected behavior**
I should be able to purchase TS51 since it shows that I have 3 TTs, but I am unable to do so.

**Screenshots**
![image](https://user-images.githubusercontent.com/57739806/219873424-c80273e3-ccce-4cfc-88a8-48afc42e7967.png)

**Savefile**
https://paste.ee/p/W8rQk

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
