### ISSUE TITLE
EC requirements only use the highest resources you've had while specifically looking at the study tree

### ISSUE THREAD

**Issue by L5racer** [antimatter-dimensions/mobile-issues#499]
**Describe the bug**
EC requirements only use the highest amount of a resource you've had while specifically looking at the study tree, and not anywhere else.

**To Reproduce**
1. Without looking at the study tree, meet the requirements of an EC.
2. Crunch to reduce the resource below the EC requirement.
3. Go back to the study tree without meeting the requirement again. The EC requirement won't be shown as met, and the EC cannot be bought.

**Expected behavior**
The EC requirement should have been met even though you weren't looking at the study tree, as it gets met and stays met if you look at the study tree the entire time while doing the steps.

**Screenshots**
I don't have a screenshot, but I have this video of using EC6 as an example. 
https://user-images.githubusercontent.com/125624914/219876246-a40da720-a4de-42bf-9b0b-adde025ddb9e.mp4

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
