### ISSUE TITLE
cel7 ui collection

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#500]
This is a collection for anything related to cel7-UI. Of course, I might have missed something.
Generally I tried sort this by tabs and content.
I've left cel7 tab, glyph, automator, autobuyer and alchemy tab mostly uncommented, since you'll rework those from what I've heard. Just made some slight suggestions. Feel free to cross these out. :)

General stuff:
- [x] Generally visual indicators for disabled stuff: 
- [x] Infinity Upgrades
- [x] Eternity Upgrades
- [x] Eternity Milestones
- [x] Time Studies
- [x] EP gen
- [x] Effarig rewards
- [x] V-achievements
- [x] Perks
- [x] Glyph tab
- [x] Reality Upgrades
- [x] Imaginary Upgrades
- [x] BH
- [x] Alchemy
- [x] Achievements
- [x] "show-disabled-stuff"-button in cel7 tab
- [x] Progress bar should display progress to next strike or to the point where it gets trigger
- [x] "You are currently in the Antimatter Universe" -> "You are currently in a Doomed Reality", not sure how well it would fit if you then enter a challenge to have it be "You are currently in [challenge] in a Doomed Reality" or if it would be too much text. (Note that web says "... Good luck.")
- [x] Currency display in top bar: AM, IP, EP and TT just like it is pre reality; additionally Reality Shards (this one always)

Challenges:
- [x] On web NCs reward is in strike through. I am not quite sure why tbh. I feel like it was worded differently back when strike through got added but I cannot think of why it would be worded differently. I guess it doesnt really matter since r61 gives you max AB intervals anyways.

Infinity:
- [x] 2e7 passive infinity generator shows an effect but is actually disabled in pelle (doesnt actually have an effect, just shows up like this)
- [x] Infinity Upgrades tab gets forced to shown after buying the four rows of upgrades. You've decided to hide the 2xIP mult and the offline IP gen. I think this is why the game thinks, you could still buy upgrades and that's why the tab cannot be hidden. (Just for reference: Web shows both upgrades, but locks the ability to buy them. If you just leave the two upgrades hidden, I'd mark r41 as disabled in cel7.)
- [x] RG autobuyer has the red "disabled"-color but says "ON", once you unlock it after unlocked at 3 eternities (save at 2 eternities, just do one more. https://paste.ee/p/jCJqL), gets fixed after either exiting the app (no need to clsoe, just exit and reopen) or toggling it twice (ON->OFF->ON)
- Have the third effect of decay ("increase max RGs based on rift milestones") show up like the exra RGs from studies (on the max rg buyer as "Max RGs: X + Y" where Y is the bonus) ? there's not enough space for this one
- [x] Reward from cel2 is displayed on replicanti tab, I'd leave a note about replicanti being uncapped, but now it is uncapped from pelle the upgrade

Eternity:
- [x] Study tab shows Space Theorem counter
- [x] Reality study shows a cost, which could be hidden, since it (should be) unpurchaseable.
- [x] edit study preset is a little borked. it shows the correct study list. "upon importing into an empty tree" shows all all pace splits (locked since we dont have ST in cel7). Same goes for the most bottom "Tree status after loading" which also shows all pace splits. (https://paste.ee/p/KlhLU; 2nd preset is a full tree with triads and everything). unsure if we want to filter out triads in presets. they're locked/hidden and so it wouldnt hurt to remove those from study preset strings. on the other hand, it doesnt hurt so 🤷🏻
- [x] eternity milestones, which effect is granted by pelle upgrades, should be marked with something (strike through) to show that you cannot get them from eternity count
- [x] perhaps cut off each offline gen text for EM6, EM100 and EM1000 and just say something along the liens of "disabled in doomed"  
- [x] 2e12 DT upgrade displays an effect, but should say disabled (dunno (yet) if *has* effect or not)

Reality (I'll split up glyph tab into multiple bullet points here):
- [x] since glyph tab is a looong tab with scrolling (at least rn) maybe just remove a lot of the stuff shown there. f.e. glyph filter are not needed since no more new glyphs/realitying. same for behaviour for deleted glyphs, same for purge/harsh purge/etc buttons
- [x] currenty active glyphs effects (both the pane and the glyph tooltip) dont filter out disabled effects (for reference: web adds a strikethrough, pelle specific effects given by one of the rift milestones are red colored)
- [x] "Start this Reality over" ->"Start this Armageddon over", also the "Unequip Glyphs on Armageddon"
- [x] reality/armageddon reset modal
- [x] Some perks and reality and imaginary upgrades are disbaled. either strike through, or mark the reward as disabled or both or something else, idk
- [x] "Unleash BH" button for 100 RM and the slider to invert BH are shown. related: #410 
- [x] check for whatever you've planned for glyph alchemy :)

Celestials:
- [x] I'll just say check other celestial tabs on web and see whats disabled since that is mostly it for those

Pelle:
- Text garble can result in tab jittering, since the first rifts reward description sometimes takes an additional line on text garbling (couldn't reproduce)
- [x] Chaos milestone (3rd rift) is a little borked. It says f.e. "9% 1 decay <br> [effect]". The "1" here is throwing me off. Also it shows both "1 decay" for first and second milestone. I assume it is rounding the 90% decay and 150% decay to 100% and then says 100% = 1 and displays 1.
- Rift filling animation (this one is hard and not needed)
- [x] Rift bar progress
- [x] Total remnant count would be neat to have somewhere. rn you just get them but dont actually know how many you have which feels weird. I know they dont really have an effect other than producing shards but still. Related: Maybe the remnant gain display (similar to glyph level and final level, see web)
- [x] Maybe the "disabled stuff in doomed" button/info/thingy as mentioned at the top of this list

Achievements:
- [x] Achievements tab (still show rewards on tooltips; perhaps just cut the achievement mult text into "All mults have been disabled" or smth like that)

Options:
- [x] "Glyph Undo" confirmation got nuked which leaves confirmations... in a weird layout with one empty spot.

Additions:
- Cel7 upgrade tooltip stays visible when upgrade becomes purchasable (actually that also goes for other tooltips, like dilation ones) idk how to fix this one
- [x] Maybe add an option to hide bought upgrades
- Upgrades added by Pelle (5th rift, 2nd milestone) have a different UI than normal/pre reality dilation upgrades (don't understand this one)
- [x] Armageddon button cropped on Oppo A53 reported by Gaunter #1337 (ID: 324171124852391936, at: https://discord.com/channels/351476683016241162/554713718282256391/1076916360753467502)

**Comment by lrobt97** [comment]
Remnant button has partial cropping on Oppo A53

**Comment by lrobt97** [comment]
![Screenshot_2023-02-19-12-17-13-89_a1dfedc045cf59f718484c5373a1c563](https://user-images.githubusercontent.com/69146855/219966076-b227f5b4-c6b4-4836-af70-f50e862a7575.jpg)

**Comment by Hirame1** [comment]
Garble text in 3rd Strike doesn't use monospace font, so it's jittering.

![image](https://user-images.githubusercontent.com/56225774/220097731-252b9779-b7b9-4644-9a22-1f1f26ef6f57.png)

**Comment by kajfik** [comment]
Implemented in 2.111.0i19
