### ISSUE TITLE
Concentration in Cel 5 doesn't slow down memory chunk gains on unselected pets

### ISSUE THREAD

**Issue by lrobt97** [antimatter-dimensions/mobile-issues#501]
With concentration selected, the targeted pet has a 3× memory chunk gain. However on web the other pets that haven't been selected will also have their speeds halved.

Additionally, I think the web version has different level scalings than what is currently present on mobile but I am not sure on this.

**Comment by kajfik** [comment]
Fixed in 2.111.0i15
