### ISSUE TITLE
Cel 5 Reward Icon Partially Cropped 

### ISSUE THREAD

**Issue by lrobt97** [antimatter-dimensions/mobile-issues#504]
![Screenshot_2023-02-18-09-44-28-25_a1dfedc045cf59f718484c5373a1c563](https://user-images.githubusercontent.com/69146855/219881352-a216898f-49c9-469e-9bd8-9594d0c93cd1.jpg)

The level 25 reward icon (the furthest to the right icon) for all pets is partially cropped.

**Comment by kajfik** [comment]
Fixed in 2.111.0i18
