### ISSUE TITLE
r184, r185 and r187 didn't trigger

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#509]
**Describe the bug**
Titel.

**To Reproduce**
1. Get to the point where they should trigger
2. See poopoo: They dont.

**Expected behavior**
Trigger.

**Screenshots**
![Screenshot_20230218-232751_a1dfedc045cf59f718484c5373a1c563.jpg](https://user-images.githubusercontent.com/66326188/219902151-eb3d1b51-f3f0-4254-aefa-0dbe096b24aa.jpg)

**Savefile**
I only have my save file on which I've realized the thing and that's sitting in dilation around e30..
https://paste.ee/p/EmCSt

**Additional content**
I do appreciate all the work you've put into the game so far and I'm feeling a little bad when looking what's left. Great work so far, kaj. Really enjoyed the first android playthrough, especially since Ra was a lot of fun with timeskips! :kekl:
I'll continue to poke around the game and report stuff. If there's something I could do, feel free to throw a message or ping at me :blobheart:

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
