### ISSUE TITLE
Lai'tele Destabilisation Reward to be shown in scientific notation on pop up

### ISSUE THREAD

**Issue by lrobt97** [antimatter-dimensions/mobile-issues#514]
When the pop up appears for destabilising Lai'tela, the reward is shown in full. It would be nice for this to display in scientific notation instead so it's easier to read (or rather it should match the chosen notation)

**Comment by lrobt97** [comment]
![Screenshot_2023-02-18-20-54-32-35_a1dfedc045cf59f718484c5373a1c563](https://user-images.githubusercontent.com/69146855/219908303-4dde3ab4-5e6d-4b51-af02-5a019551295b.jpg)

**Comment by kajfik** [comment]
Fixed in 2.111.0i18
