### ISSUE TITLE
Entering Cel 7 gives me 2 effect dots Time Glyph

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#516]
**Describe the bug**
Entering Cel 7 gives me 2 effect dots Time Glyph.

**To Reproduce**
1. Import the attached save.
2. Make sure you have no Glyphs (not needed to sacrifice all Glyphs, but I did that to make it clear).
3. Enter Cel 7.
4. See all your Glyphs have 4 effect dots.
5. Restart the app.
6. See now your Time Glyph has only 2 effect dots. (And somehow that Glyph has an effect from the Dilation Glyph :blobthink: )

**Expected behavior**
Get 4 effect dots Glyphs.

**Screenshots**
Before restart.
![Screenshot_20230219-120946_Antimatter Dimensions~2](https://user-images.githubusercontent.com/56225774/219923907-a4bd215d-faad-4e8a-9b26-913a62b02f52.png)

After restart 
![Screenshot_20230219-120955_Antimatter Dimensions~2](https://user-images.githubusercontent.com/56225774/219923976-b52e336e-a913-40f8-b204-f11f8bdc138d.png)

**Savefile**
[ready for cel 7.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10776013/ready.for.cel.7.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
