### ISSUE TITLE
(Cel 7) Effect of 2nd Rift of 4th Strike looks not applied

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#517]
**Describe the bug**
It looks effect of 2nd Rift of 4th Strike is not applied.

**To Reproduce**
1. Import the attached save.
2. Go to Cel 7 tab.
3. See effect of 4th Strike.

**Expected behavior**
I have 34 EC completions, so I think there should be an effect already.

**Screenshots**
![image](https://user-images.githubusercontent.com/56225774/219946217-a53c7cda-217b-4524-9dff-13322c1a7698.png)

**Savefile**
[34 ec completions in cel 7.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10776788/34.ec.completions.in.cel.7.txt)

**Comment by L4R5W** [comment]
It starts to have an effect after 45 total completions... Which essentially means get ec10 done which means like e120 EP or more. The early unlock is...weird game design...

The formula for it is something like `max(number ^ ((EC completions - 25) / 20), 1)`.

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
