### ISSUE TITLE
Misaligned text in break infinity upgrades

### ISSUE THREAD

**Issue by Kloetzchen** [antimatter-dimensions/mobile-issues#518]
**Describe the bug**
After breaking infinity the text for some upgrades is misaligned. Fixed after restarting the game after purchasing the upgrades 

**To Reproduce**
1. Break infinity

**Expected behavior**
Center alignment like the other upgrades

**Screenshots**
![IMG_20230217_233551](https://user-images.githubusercontent.com/125806336/219950420-a0456430-1531-41f9-aa24-85c275a54df9.jpg)

**Savefile**
I don't have a save file to showcase this at the moment, can provide one later if necessary.

**Comment by kajfik** [comment]
This is a known android OS bug, idk how to fix.
