### ISSUE TITLE
Dynamic scaling for crunch autobuyer based on Pelle strikes 

### ISSUE THREAD

**Issue by lrobt97** [antimatter-dimensions/mobile-issues#519]
Filling the first rift increases the IP gained multiplier. However this currently isn't accounted for in the autobuyer settings. As this is the one of the few ways of boosting IP gain in cel 7 it would be nice to have the autobuyer scaling adjust based on this.

**Comment by kajfik** [comment]
this is a nice idea but it doesn't exist on web, once it exists on web I can implement it on mobile too
