### ISSUE TITLE
(Cel 7) Progress bar for EC shows goal of earlier Tier while I'm doing later Tier

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#520]
**Describe the bug**
Progress bar for EC shows goal of earlier Tier while I'm doing later Tier.
(I realized this while I'm in Cel 7. I'm not sure what is triggering it...)

**To Reproduce**
1. Enter EC that has 1~4 completions.
2. Tap progress bar to see the goal amount.
3. See the goal amount shown in the Eternity button and the progress bar is different.

**Expected behavior**
Shows correct goal amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/56225774/219957149-66e61948-c8de-4caa-b66f-c755cab0c41f.png)

![image](https://user-images.githubusercontent.com/56225774/219957154-336c9bf7-a95f-4658-b43f-36179bc2b174.png)

**Savefile**
[ec goal for later tier in cel 7.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10777195/ec.goal.for.later.tier.in.cel.7.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
