### ISSUE TITLE
Infinite Replicanti countdown timer too slow when repl. chance is at around 17%

### ISSUE THREAD

**Issue by msiitan** [antimatter-dimensions/mobile-issues#523]
**Describe the bug**
The countdown timer for the time until infinite replicanti counts down too slowly in early Eternity phase when Replicanti chance is at around 17%. More specifically, 1s of the countdown takes about 1.5-1.7s real time, possibly even slower at lower chance percentages. This also occurs at lower chances, but when the chance is above 20-25%, the issue no longer persists and the timer counts down at the correct speed. 

**To Reproduce**
1. Open save
2. Keep auto replicanti upgrades disabled to stay at the same chance and interval
3. Observe countdown timer

**Screenshots**
![AD Slow replicanti timer](https://user-images.githubusercontent.com/80489175/220130058-742a4c86-7c98-49ba-9e8c-4688f47e0bc4.gif)

**Savefile**
https://pastebin.com/JhS3WgXR
(paste still pending moderation at the time of posting)

[Slow Replicanti timer_230220_014633.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10785134/Slow.Replicanti.timer_230220_014633.txt)

**Comment by gerritimmink** [comment]
I'm seeing this issue as well but only while the game is offline. I'm in reality 2, with low Rep Chance levels (12 or 13%) 

I'm adding a pair of screenshots where Real time (as shown by the System Clock) progressed 85 seconds (while offline) but Replicanti only progressed 43 Seconds.

That said, I dont see this issue while the app is open.

Android 13, Pixel 5a
![Screenshot_20230308-210928](https://user-images.githubusercontent.com/126215489/223930649-b42436da-2957-48cc-861e-55e827b1f7bf.jpg)
![Screenshot_20230308-211053](https://user-images.githubusercontent.com/126215489/223930653-9f7d450f-e520-4af1-9b19-c8dc7b8a8394.jpg)

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
