### ISSUE TITLE
News ticker slowdown effects don't reset on Reality

### ISSUE THREAD

**Issue by L5racer** [antimatter-dimensions/mobile-issues#527]
**Describe the bug**
Pressing Reality while inside EC12 or dilation doesn't reset the slowdown effect on the news ticker until you restart the app. This can be repeated, allowing you to stack slowdowns infinitely.

**To Reproduce**
1. After unlocking the Reality study, enter EC12 or dilation.
2. Reality while still inside either EC12 or dilation.
3. The slowdown effect will stay, and you can repeat steps 1 and 2 to stack slowdowns.

**Expected behavior**
The speed of the news ticker should've been reset to normal on Reality.

Video of me stacking the slowdown effect a few times: https://discord.com/channels/351476683016241162/554713718282256391/1077369579963154522

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
