### ISSUE TITLE
Equipped glyphs change level to projected level

### ISSUE THREAD

**Issue by TheCubeDude** [antimatter-dimensions/mobile-issues#529]
**Describe the bug**
When the projected glyph level is higher than the current equipped glyph level, clicking on an equipped glyph changes the level of that glyph to the projected level.

**To Reproduce**
1. Get to a projected glyph level higher than that of your current glyph level
2. Click on an equipped glyph
3. Click somewhere else to hide the information box
4. Click back on the same glyph once glyph level has increased
5. See the equipped glyph change levels

**Expected behavior**
Self-explanatory, equipped glyphs should not change level

**Savefile**
https://textbin.net/pbc9puqqxr

**Additional context**
One of the potential glyphs has the same effects as the glyphs I clicked on
![Screenshot_20230221_212432_Antimatter Dimensions](https://user-images.githubusercontent.com/125773349/220515434-ee10a151-3de9-4781-b6b1-c375a9fcfcc3.jpg)
![Screenshot_20230221_212424_Antimatter Dimensions](https://user-images.githubusercontent.com/125773349/220515451-aecc7d2f-d526-4c6b-92c5-2bf106c87696.jpg)

**Comment by TheCubeDude** [comment]
Additional information: increased level persists after unequip

**Comment by TheCubeDude** [comment]
Additional additional information: bug went away after going to another app

**Comment by Kloetzchen** [comment]
I encountered the same bug, but it seems to have permanently increased the affected glyph levels, see currently equipped lvl67 glyphs:
https://paste.ee/p/MIM1p

**Comment by TheCubeDude** [comment]
I mentioned that that happened to me in one of my additions.

**Comment by Kloetzchen** [comment]
Sorry, i read your comments as that it was resolved after switching app/restarting. Ignore my comment then.

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
