### ISSUE TITLE
option to automatically move glyphs on changing protected row count

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#531]
**Is your feature request related to a problem? Please describe.**
I personally like to only protect some effarigs. Chaning protected row count is usually annoying since  you end up with having your first not-protected row being protected and you need to move glyphs down one by one.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/66326188/220992196-9614a52c-379d-44fe-8143-d07a008d76e9.png)

**Describe alternatives you've considered**
~~Dont give an option. Force it to move.~~

**Additional context**
if the (un)protected rows are already completely full, then it should just add/remove 1 to/from protected row count without moving any glyphs (see web behaviour)

**Comment by kajfik** [comment]
Added in 2.111.0i18
