### ISSUE TITLE
Offline Progress Not Running 

### ISSUE THREAD

**Issue by gerritimmink** [antimatter-dimensions/mobile-issues#532]
**Describe the bug**
I'm No longer able to make any meaningful progress while offline.
I'm in the early reality era (e3 RMs), and I started seeing this issue intermittently a few days ago, where it seemed to get in a state where it wouldn't process offline ticks. Today it has now become a permanent issue. 

Now whenever I leave the app, and reopen later, the game will not have progressed at all. Switching to "Offline Progress SHOWN" (from Hidden) I get a popup that something happened, but its an incredibly small change, like only a few ticks. 

**Configuration**
App Version 2.111.0i5
Google Pixel 5a
Android 13, Feb 5, 2023 Security Update.
UI Update Rate 50ms
Max Offline Tics 1,000,000
UI updates during offline progress ON

**To Reproduce**
1. Open the app,
2. Perform an action (I like to eternity to trigger a bunch of autobuyers etc)
3. Leave the app, noting the value of something at the time, like pending EP (Home button for me)
4. Wait a period of time (the duration doesn't matter, but to reinforce the bug wait minutes or hours
5. Reopen the app
6. Observe that the value you noted earlier, will not have changed until you reopen the app. 

**Expected behavior**
Offline Progress should compute, giving you a best effort interpretation of your time away 
 
**Screenshots**
![Screenshot_20230223-074159](https://user-images.githubusercontent.com/126215489/221071667-4903d512-5712-44dd-824b-c566246114ac.jpg)
Attached is a screenshot showing the offline progress popup, where it says my IP increased from e4381 to 4384, but you can see on the Big Crunch Button in the Top Right, that the next Pending IP is E5460 (the autobuyer was set to e50 Max and bought correctly on exiting the dialog, it just didn't do anything offline, that's all from it processing between when I opened the app and took the screenshot. 

**Savefile**
https://pastebin.com/gD4qNHY6

**Additional context**
I tried clearing cache, which didn't help, I'm planning on trying clearing data and/or reinstalling to see if that fixes it, and for how long.

**Comment by gerritimmink** [comment]
Another note; It seems to know about the passage of time, as things like the real time duration of the current reality on the statistics tab, and the duration of black hole activity properly changes (though black hole bonuses don't seem to do anything here either)

**Comment by gerritimmink** [comment]
Well I cleared app data (not just cache) and loaded my save and... it processed half an hour of offline time. Not sure what that indicates, but may help.

**Comment by kajfik** [comment]
Could you please share a savefile that reproduces this issue? The above pastebin link doesn't work.

**Comment by JohanniklasLp** [comment]
I have the same issue, however only of my "max offline ticks" are on a low value. If I set them to a high value, offline progress is normal.

**Comment by kajfik** [comment]
can't reproduce
