### ISSUE TITLE
Descriptions and boxes for TTS and SAM perks blacked out

### ISSUE THREAD

**Issue by NiZeKiHo** [antimatter-dimensions/mobile-issues#536]
**Describe the bug**
The boxes for TTS and SAM are blacked out with no text when they are purchasable.

**To Reproduce**
Not sure if this is the exact correct steps, but it is what caused it for me
1. Update to 2.111.016
2. Reality
3. Go to Perk tab, and have a perk point available
4. See TTS and SAM being blacked out if you don't have them but are able to buy them

**Expected behavior**
I expected TTS and SAM to have a grey background with black text.

**Screenshots**
![image](https://user-images.githubusercontent.com/66221827/221429958-b892ce92-eda2-46f4-92f6-c644edbdf888.png)

**Savefile**
https://paste.ee/p/wgKp0

**Additional context**
This was my first time doing a Reality after 2.111.016, not sure if that is the cause or not.

**Comment by kajfik** [comment]
Fixed in 2.111.0i7
