### ISSUE TITLE
Unable to buy second row Eternity Upgrades

### ISSUE THREAD

**Issue by NiZeKiHo** [antimatter-dimensions/mobile-issues#537]
**Describe the bug**
Unable to buy 4th Eternity Upgrade, despite having 7 OoMs higher than needed

**To Reproduce**
I have no idea what made this be the case, my guess is the newest update

1. Be on 2.111.016
2. Reality
3. Get to 1e16+ EP without having 4th Eternity Upgrade
4. Try to buy said upgrade, which won't work.

**Expected behavior**
I expected the upgrade to be bought

**Screenshots**
![image](https://user-images.githubusercontent.com/66221827/221431951-98b5d024-8cf7-4fb8-a1cb-aee26ea90875.png)

**Savefile**
My own savefile, with EU4 available but not purchasable: https://paste.ee/p/sSGY7
Savefile provided to be, unable to purchase EU4, EU5 and EU6: https://paste.ee/p/sSGY7

**Comment by kajfik** [comment]
Fixed in 2.111.0i7
