### ISSUE TITLE
Can't purchase TS despite having enough TT

### ISSUE THREAD

**Issue by Kloetzchen** [antimatter-dimensions/mobile-issues#538]
**Describe the bug**
Can't purchase TS 101 (cost 4TT) despite having 4 TT.

**To Reproduce**
1. Import provided save file
2. Check time studies

**Expected behavior**
Being able to purchase a time study when the displayed amount of TT matches the cost of the time study

**Screenshots**
![Screenshot_2023-02-26-22-40-57-798_kajfosz antimatterdimensions](https://user-images.githubusercontent.com/125806336/221439290-f0653985-876a-40d6-8927-b61e2dd1006c.jpg)

**Savefile**
https://paste.ee/p/57qg1

**Additional context**
Probably related to TT generating glyph

**Comment by NiZeKiHo** [comment]
Yeah. This is a rounding issue, since lower TT/hr glyphs give you like.. 1.04 per hour, so if you have 4.75 TT it probably visually rounds up to 5

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
