### ISSUE TITLE
Remove manual reality animation after some realities

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#539]
**Is your feature request related to a problem? Please describe.**
Manually reality-ing (if that's a word) still does the crunch animation even after a lot of realities

**Describe the solution you'd like**
Remove the animation after 10 realities (something similar to the infinity animation)

**Comment by Clarissa-Valentine-Z** [comment]
Not to barge in, but I believe this has been implemented in the Options, under Animations, there should be an option to turn Reality Animations on or off.

**Comment by The-Chosent-One** [comment]
Ah yeah, didn't realise that

**Comment by kajfik** [comment]
Won't implement, closing the issue
