### ISSUE TITLE
Duplicate AP gains

### ISSUE THREAD

**Issue by ahmeteris** [antimatter-dimensions/mobile-issues#540]
![Screenshot_20230228_121953_Antimatter Dimensions](https://user-images.githubusercontent.com/41326172/221827240-7a56c479-50d3-489e-a87c-f2fedf6dd5fd.jpg)
Automator screens shows AP gains two times. The ones on the left are not needed.

**Comment by kajfik** [comment]
Fixed in 2.111.0i9
