### ISSUE TITLE
Cel7 - Unable to unlock an upgrade even with enough Reality Shards.

### ISSUE THREAD

**Issue by Clarissa-Valentine-Z** [antimatter-dimensions/mobile-issues#543]
**Describe the bug**
On engineering notation, at least, it would have seem like some of the upgrades need a little bit more than the required amount in order to be purchased. Please see screenshot below.

**To Reproduce**
1. Go to Pelle Celestial.
2. If needed, get the Reality Shards as close, and meeting or slightly exceeding the needed RS for an upgrade.

**Expected behavior**
Should be able to buy, for example, 1e27 RS upgrade with 1.25e27 in hand. I believe it may not be a rounding issue, as it used Engineering Notation.

**Screenshots**
![Screenshot_20230301-094957](https://user-images.githubusercontent.com/71510824/222028083-c14aee81-8830-4e95-883a-51964eab080f.png)
![Screenshot_20230301-095003](https://user-images.githubusercontent.com/71510824/222028094-b542a5a0-2e07-4b5d-8d66-efa4aadce4b0.png)

**Savefile**
I unfortunately progressed past the point of the bug but here it is if needed. Here it is if needed. 
[sem título.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10856509/sem.titulo.txt)

**Comment by msiitan** [comment]
I noticed this too, using scientific notation. It's basically just a decimal precision inconsistency: the 5 rebuyable upgrades use no decimal places, while the one-time purchases use 2 decimal places. The game speed rebuyable upgrade definitely needs decimal places as well, since it doesn't scale by a factor of 10.

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
