### ISSUE TITLE
Too many particles on screen

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#544]
**Describe the bug**
I see too many particles flying on my screen.

**To Reproduce**
1. Import save 1 to any slot.
2. Open TD tab.
3. (Optional) open another save slot.
4. Import save 2.
5. Open TD tab.
6. See you have many particles.

Another reproduction step:
1. Import save 1
2. Turn on TP animation in Options.
3. Open TD tab.
4. See you have many particles. (Is that normal particle amount at the end of Cel 6 stage?)

![Screenshot_20230301-074802_Antimatter Dimensions](https://user-images.githubusercontent.com/56225774/222053349-70c787fd-f996-4962-86f7-d57ca360fea7.png)

**Savefile**
[save 1.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10857432/save.1.txt)
[save 2.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10857433/save.2.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
