### ISSUE TITLE
Misspelling of Relic as Reality

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#545]
**Describe the bug**
After unlocking Effarig and performing a manual reality, it tells the user it gains Reality shards instead of Relic shards

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Go to Reality tab
2. Click on the reality button
3. Before manually reality-ing, the popup with the wrong term is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/57739806/222205447-88fc4825-6ce1-476b-902f-0b7ea64e2f97.png)

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
