### ISSUE TITLE
am idiot mark as closed

### ISSUE THREAD

**Issue by RqzorPhoenix** [antimatter-dimensions/mobile-issues#546]
**Describe the bug**
Blackhole doesn't seem to be affecting DT gain
**To Reproduce**
1. Just use blackhole anytime during dilation phase

**Expected behavior**
(pretty obvious, it should multiply the dt gain per hour)

**Screenshots**

https://user-images.githubusercontent.com/94931807/222403332-6c397dd8-5467-4764-9a99-d41d0357ad66.mp4

**Savefile**
https://paste.ee/p/2sLnm

**Comment by lrobt97** [comment]
I think that's giving the real time DT/hr rather than game time, what does web do?
