### ISSUE TITLE
Achievement 142 is not granted upon automator unlock

### ISSUE THREAD

**Issue by davixx95** [antimatter-dimensions/mobile-issues#547]
**Describe the bug**
When i unlocked the automator with the ECB perk granting 15 automator points the automator interface was unlocked, but the achievement remained locked, I saw a user claiming the very same bug on Discord, the minor difference is they unlocked the automator with a Reality Upgrade.

**To Reproduce**
1. Use a save that has near 100 automator points
2. Buy a reality upgrade or unlock a perk that should put you over 100 automator points.

**Expected behavior**
The moment the automator points exceed 100 the achievement should be unlocked along the automator UI.

**Screenshots**

**Savefile**
[Link to the broken save](https://paste.ee/p/Ux59j)

**Additional context**

**Comment by kajfik** [comment]
Fixed in 2.111.0i9
