### ISSUE TITLE
"Painful" notations cause a crash

### ISSUE THREAD

**Issue by ReacTivity1** [antimatter-dimensions/mobile-issues#548]
When using "painful" notation (Emoji, Blob, Standart etc) checking achievements using the exponent source number (e[N]) crash the game instantly.

Reprodusable: yes
Who can reproduce: mostly everyone
Platform: mobile
Version: 2.111.0i8 (internal testers)

Steps to reproduce:
1. Change your notation to "painful" which uses ginormous number of script numbers
2. Go to "Achievements" tab
3. Tap on something which has "[M]e[E]" form of number in it ("Yo dawg, I heard you liked Infinities", "Deep fried", "IT'S OVER 9000" etc)
4. Observe

Normal behaviour: the achievement you tapped will show it's requirement and reward (if available)
Current behaviour: the game crashes

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
