### ISSUE TITLE
"You have no Banked Infinities"

### ISSUE THREAD

**Issue by ReacTivity1** [antimatter-dimensions/mobile-issues#549]
**Description:**
It would be great if Stats screen would say "You have no Banked Infinities" when you have no one of them, but can get them this Eternity

**Current behaviour:**
When on Stats screen, you won't see this line if you have no BInf-s, even if you can Eternity to gain them. You'll only see the "You will gain [N] BInf-s" line.

**New feature:**
It will show "You have no BInf-s" if you really do, but can get them.

**Possible uses:**
When unlocked r131 achievement or TS191 this Eternity, you can see that you're actually able to get BInf-s after you Eternity. Useful if you unlocked r131 without noticing it with Reality's auto-achievement feature.
Useful for people who look at this line too frequently and can be stunned a bit if lose it after Reality with no Eternities.

**Downsides:**
None, since Stats can be scrolled down and up.

**Note:**
Not too important to have, but will improve QoL if you know what BInf-s are and wrere they can be used.
![IMG_20230303_234648](https://user-images.githubusercontent.com/126914916/222828567-3e458ecc-c238-47d0-8f2a-6e5939a92187.jpg)

**Comment by kajfik** [comment]
Implemented in 2.111.0i18
