### ISSUE TITLE
Time Dimension Autobuyer On/Off state is not saved

### ISSUE THREAD

**Issue by neoiw** [antimatter-dimensions/mobile-issues#550]
**Describe the bug**
TD Autobuyer's on/off status changes to on by itself when reloading the game/going offline.

**To Reproduce**
1. Turn off the TD Autobuyer.
2. Go offline.
3. Get back online.
4. TD Autobuyer will be on

**Expected behavior**
TD Autobuyer should stay off.

**Screenshots**

https://user-images.githubusercontent.com/45356936/222887369-c24029fc-99ea-4506-933e-20999d606837.mp4

**Savefile**
[TDAuto.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10886130/TDAuto.txt)

**Additional context**
I _think_ I also experienced this issue while browsing other tabs (Eternity tabs iirc), but I was not able to reproduce it.

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
