### ISSUE TITLE
Replicative Rapidity shouldn't say Best if no realities

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#551]
**Describe the bug**
After unlocking reality the first time the reality upgrade Replicative Rapidity shows an effect with "Best: xxxx".

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Load save or any save that has reality unlockable but never realities
2. Go to reality upgrades
3. Scroll down
4. See error "best: xxxx"

**Expected behavior**
Don't show "Best: xxxx" if player has no realities since there is no fastest reality yet.

**Screenshots**
![Screenshot_20230304-222033_a1dfedc045cf59f718484c5373a1c563.jpg](https://user-images.githubusercontent.com/66326188/222929195-29017ea0-3b0f-408a-8762-fdfc00259bec.jpg)

**Savefile**
https://paste.ee/p/0X1sW

**Additional context**
Nice

**Comment by L4R5W** [comment]
That save went through a lot of weird stuff. However, also happens on savebank saves: this is the e6978 save from savebank which I cannot add here as a txt file I hate mobile GitHub... Just grab a save from the bank ._. I am heading to bed :blobgoodnight:

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
