### ISSUE TITLE
Quality of Life for Cel 3/Nameless

### ISSUE THREAD

**Issue by NiZeKiHo** [antimatter-dimensions/mobile-issues#552]
**Is your feature request related to a problem? Please describe.**
I got frustrated and felt stuck during Enslaved/Nameless reality as I knew I was supposed to use ec6, but had completely forgotten that i had to enable a setting to even be able to redo eternity challenges

**Describe the solution you'd like**
I would like the setting to be locked to, or at least automatically switched to "On" during the Reality, so me and other people won't end up feeling stuck or not realizing it's an option

**Comment by kajfik** [comment]
Fixed in 2.111.0i18
