### ISSUE TITLE
Triad study ID and name visible in Cel 7

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#553]
**Describe the bug**
Triad study ID and name visible in Cel 7

**To Reproduce**
1. Import save 1
2. Open STUDIES tab
3. Do any of these : Import save 2 / Unlock Cel 7 and Doom / Change save slot that is in Cel 7
4. Open STUDIES tab
5. See Triad study's ID and name are visible

**Screenshots**
![image](https://user-images.githubusercontent.com/56225774/222940745-cac441c5-2e4f-4ddf-8281-bc58cd9af63f.png)

**Savefile**
save 1
[end of cel 6.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10890757/end.of.cel.6.txt)
save 2
[in cel 7.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10890758/in.cel.7.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
