### ISSUE TITLE
V unlock requirements: white text on white background when using Light theme

### ISSUE THREAD

**Issue by msiitan** [antimatter-dimensions/mobile-issues#554]
Title says it all. Happens when using the light theme (night mode off)
Screenshot:
![Screenshot_20230305-025247_Antimatter Dimensions](https://user-images.githubusercontent.com/80489175/222965747-83f9288f-a056-481d-9f27-43646164988f.jpg)

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
