### ISSUE TITLE
Hold to continuously buy rebuyable reality upgrades

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#557]
**Is your feature request related to a problem? Please describe.**
The only way to buy rebuyable reality upgrades is to keep tapping them. It would be more convenient for there to be a "hold to buy continuously" feature for them

**Describe the solution you'd like**
Hold to buy continuously buy the rebuyable reality upgrades

**Comment by kajfik** [comment]
Implemented in 2.111.0i18
