### ISSUE TITLE
Ra's level pop-up not properly resized

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#558]
**Describe the bug**
When levelling up Ra's different levels, the pop-up should be resized to the next level's size accordingly

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Import save
2. Go to Ra's celestial
3. Try upgrading any of the memories repeatedly

**Expected behavior**
The pop-up should be resized accordingly whenever an upgrade is bought

**Screenshots**
https://user-images.githubusercontent.com/57739806/223395193-9ad7566d-1a17-44e3-a07a-0b4e0019ef84.mp4

**Savefile**
https://paste.ee/p/QgoE7

**Comment by kajfik** [comment]
idk how to fix this one
