### ISSUE TITLE
Replicanti effect text overflows out of the screen

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#559]
**Describe the bug**
The replicanti description for "multiplying DT gain and Replicanti speed by x from Glyphs" overflows out of the screen

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Import save
2. Go to replicanti tab
3. See error

**Expected behavior**
Expect the text to not overflow out of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/57739806/223397644-267547ae-b134-4240-bd28-6d71345a36fe.png)

**Savefile**
https://paste.ee/p/iyPYt

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
