### ISSUE TITLE
Display for respec-ing charged inf upgrades stays lit after reality-ing

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#560]
**Describe the bug**
The display for the option to Respec Charged Infinity Upgrades stays turned on even after Reality-ing. The state of the respec seems to be accurate, just not the display.

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Import save
2. Go to Infinity tab, click respec
3. Reality
4. Go back to the infinity tab

**Expected behavior**
The display for the button should go back to normal after a reality.

**Screenshots**
https://user-images.githubusercontent.com/57739806/223400841-f03231f0-d6b3-48cf-840a-eec218f1b98d.mp4

**Savefile**
https://paste.ee/p/ARdcA

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
