### ISSUE TITLE
Ra's memory icons doesn't fit perfectly on screen

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#561]
**Describe the bug**
The icons for different "milestone" levels don't fit perfectly on screen

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Import save
2. Go to Ra's tab
3. See error

**Expected behavior**
It should fit nicely on screen

**Screenshots**
![test](https://user-images.githubusercontent.com/57739806/223754494-a6771022-7e0c-4ca7-a459-eb3de4e6f42c.png)

**Savefile**
https://paste.ee/p/UVwra

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
