### ISSUE TITLE
Detailsof Hard V challenges overflow out of hexagon

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#562]
**Describe the bug**
Details of the challenges, such as the title, or the glyphs used previously in a challenge don't fit perfectly in the hexagon

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Import save
2. Go to V celestial tab
3. Click "Show Hard V"

**Expected behavior**
The words should fit nicely in the hexagon

**Screenshots**
![test](https://user-images.githubusercontent.com/57739806/223756078-e29b68e8-d81e-449b-b7b1-baaa3487a87e.png)

**Savefile**
https://paste.ee/p/UVwra

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
