### ISSUE TITLE
Remove large space between Hard V challenges and V achievement milestones

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#563]
**Describe the bug**
There's a large space between the Hard V challenges and V achievement milestones

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Import save
2. Go to V celestial tab
3. Click show Hard V

**Expected behavior**
The V achievement milestones should be together with the challenges, like how the regular V challenges look

**Screenshots**
![image](https://user-images.githubusercontent.com/57739806/223757420-e836f00c-f3e8-4dfe-a31b-13e850be1307.png)

**Savefile**
https://paste.ee/p/UVwra

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
