### ISSUE TITLE
Effortless Existence not unlocking at requirement

### ISSUE THREAD

**Issue by Kloetzchen** [antimatter-dimensions/mobile-issues#564]
**Describe the bug**
Effortless Existence did not unlock after reaching the required ep (see screenshot). It unlocked on the next eternity afterwards, which was also after reality for only e10 Ep

**To Reproduce**
Probably:
1. Get > e11111 EP
2. Check reality Upgrades

**Expected behavior**
Reality upgrades should unlock after reaching the requirement 

**Screenshots**
![IMG_20230308_171738](https://user-images.githubusercontent.com/125806336/223771432-cee45d06-b8df-4be2-8d5f-f8ab3f3d5350.jpg)

**Savefile**
Unfortunately i forgot to export the save file when this happened.

- Neo -#0727's save with the same bug:
https://paste.ee/p/scjH0

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
