### ISSUE TITLE
Total Termination Shows Red When Restarting Cel2

### ISSUE THREAD

**Issue by Snaeks** [antimatter-dimensions/mobile-issues#565]
**Describe the bug**
Total Termination shows red instead of yellow when you restart Effarig's Reality by swapping out a glyph.

**To Reproduce**
1. Start Cel2 to try to complete Total Termination, but do not have 4 cursed glyphs equipped.
2. Swap out 1 glyph for a cursed glyph
3. Check on Total Termination

**Expected behavior**
Total Termination should be yellow when in cel2 and have 4 cursed glyphs equipped regardless of how you get to 4 cursed glyphs in cel2.

**Screenshots**
https://cdn.discordapp.com/attachments/1077957255586119770/1083130582621487174/Screen_Recording_20230308_125147_Antimatter_Dimensions.mp4

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
