### ISSUE TITLE
Paradoxical Forever has wrong/unclear description

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#566]
**Describe the bug**
To me the description
> Eternity for 1e10 EP without buying the 5xEP upgrade

implies I would need to gain 1e10 EP upon a single eternity when in fact it actually checks best EP, so 10 eternities for 1e9 EP each will also unlock the rupg.
Note that this, the check for *having* 1e10 EP, is consistent with web behaviour. Just description doesn't quite suite.

**Expected behavior**
Change description to something like "Have 1e10 EP without buying 5xEP upgrade."

**Savefile**
https://paste.ee/p/50aq3

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
