### ISSUE TITLE
Glyph sacrifice causes app to crash

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#567]
**Describe the bug**
When I tap `Sacrifice all Glyphs rejected by filtering` button in Cel 7, the app sometimes crash.

**To Reproduce**
1. Import the attached save
2. Open Glyphs tab
3. Tap `Sacrifice all Glyphs rejected by filtering` button
4. Repeat (3) until app crashes

**Savefile**
[cel 7 crash.txt](https://github.com/antimatter-dimensions/mobile-issues/files/10943431/cel.7.crash.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
