### ISSUE TITLE
cannot use variables in until statements in automator

### ISSUE THREAD

**Issue by Kloetzchen** [antimatter-dimensions/mobile-issues#568]
**Describe the bug**
If you try to use a variable in an until statement the next { is ignored. {{ works to start the block though.

**To Reproduce**
Go to automator, type:

define target = 1e10
until pending rm > target {
 ...
}

**Expected behavior**
First { should be recogniced

**Screenshots**
[Screenshot](https://cdn.discordapp.com/attachments/554713718282256391/1083827982591856721/Screenshot_2023-03-10-20-05-13-99_a1dfedc045cf59f718484c5373a1c563.jpg)

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
