### ISSUE TITLE
Crashes and unintended behaviour with glyphs

### ISSUE THREAD

**Issue by The-Chosent-One** [antimatter-dimensions/mobile-issues#569]
**Describe the bug**
Whenever a glyph is tapped on, it shows a pop-up of the effects of the glyph. This pop-up _only_ gets closed if the user taps anywhere else or performs an action such as sacrificing/equipping. This can be used to perform crashes and abused in one case to infinitely sacrifice/refine a single glyph.

**Crashes**
- Equipping more than the maximum number of glyphs
1. Go to Glyph tab
2. Equip 3/4 glyphs (leave one slot empty)
3. Click two unequipped glyphs in quick succession such that both pop-ups are on screen.
4. Equip both glyphs. The game should crash after equipping the second glyph.

Video showing the crash:
https://user-images.githubusercontent.com/57739806/224536628-b297de7c-800e-4e01-aac6-47904d3fd29c.mp4

- Attempting to equip a deleted glyph
1. Go to Glyph tab
2. Have at least one glyph slot empty
3. Click on an unequipped glyph twice in quick succession such that two pop-ups are shown
4. Sacrifice/refine the glyph
5. Try to equip it

Video showing the crash:
https://user-images.githubusercontent.com/57739806/224537075-62aa7323-29f3-44e9-8940-c8cb6f71be2e.mp4

Reversing steps 4/5 allows one to infinitely sacrifice/refine a glyph. The game seems to be fine with allowing sacficing/refining a deleted glpyh.

**Infinite glyph sacrifice**
1. Go to Glyph tab
2. Have at least one glyph slot empty
3. Click on an unequipped glyph twice in quick succession such that two pop-ups are shown
4. Equip the glyph
5. Sacrifice/refine the glyph for the reward

Video showing the unintended behaviour:
https://user-images.githubusercontent.com/57739806/224537261-f221a6f2-5da3-4557-8e9c-1de6b4b13302.mp4

**Comment by kajfik** [comment]
Fixed all three issues in 2.111.0i14
