### ISSUE TITLE
BH gets activated upon upgrading despite set to paused

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#570]
**Describe the bug**
BH gets activated if upgrading it would put it into an active state, despite having it set to auto pause before activation.

**To Reproduce**
1. Load save
2. Goto BH tab, check that BH is set to pause before activation
3. Upgrade BH interval (need to be quick, only 7 sec on clock)
4. See poopo, BH gets activated

**Expected behavior**
Pause BH before activation.

**Screenshots**
Uploading 23-03-14-11-25-59_a1dfedc045cf59f718484c5373a1c563.mp4…

**Savefile**
If applicable, add a pastebin link with a savefile.
https://paste.ee/p/vZv75

**Additional context**
Maybe change the template for "Savefile" to not ask for a pastebin link but for a paste.ee link.

**Comment by kajfik** [comment]
![image](https://user-images.githubusercontent.com/20711517/227960050-2b4f1ea3-8e2f-4cfd-9471-a09f4cf48fad.png)
kekl

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
