### ISSUE TITLE
glyph rarity is OP pls fix

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#571]
**Describe the issue**
![image](https://user-images.githubusercontent.com/66326188/225093013-d04e67b1-f0e3-4189-92b9-b225af1c3a26.png)

**Describe the solution you'd like**
~Make glyphs on web have same rarity as on mobile.~

**Describe the solution that should be implemented in the end**
Make glyphs on mobile have same rarity as on web.

**Additional context**
Save file with glyphs as above on reality
https://paste.ee/p/vcROd

**Comment by kajfik** [comment]
Fixed in 2.111.0i11
