### ISSUE TITLE
ad button text doesn't change with r143

### ISSUE THREAD

**Issue by Calmcat5** [antimatter-dimensions/mobile-issues#572]
![Screenshot_20230314-162937](https://user-images.githubusercontent.com/94936969/225131225-cced2cef-9e32-4b5d-9cee-889c2e3d4c37.png)
see screenshot. r143 was not unlocked recently on my save, it was some days ago.

**Comment by Calmcat5** [comment]
where labels

**Comment by kajfik** [comment]
Implemented in 2.111.0i18
