### ISSUE TITLE
Ra late memory upgrades not working or capped but not showing the cap

### ISSUE THREAD

**Issue by msiitan** [antimatter-dimensions/mobile-issues#573]
**Describe the bug**
When buying late memory or memory chunk upgrades for a celestial in Ra's tab, the upgrades do not work properly or are capped, but this information is not displayed (on web, they would be capped after some point).

**Screenshots**
![Ra late memory upgrade purchase bug](https://user-images.githubusercontent.com/80489175/225156977-427061b6-6fc1-4a70-be4b-b256eedf1e07.gif)

**Savefile**
https://paste.ee/p/AZJkl

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
