### ISSUE TITLE
Eternity Autobuyer's setting is always rounded

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#574]
**Describe the bug**
Eternity Autobuyer's setting is always rounded to the closest whole number after change to the other tab.

**Screenshots**
![Screenshot_20230316-164100_Antimatter Dimensions~2](https://user-images.githubusercontent.com/56225774/225584375-e8b39f33-4fb7-4227-be79-08c413ce1f45.png)
After change to the other tab:
![Screenshot_20230316-164117_Antimatter Dimensions~2](https://user-images.githubusercontent.com/56225774/225584402-205aeca1-b971-4076-9364-707ea7a64d17.png)

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
