### ISSUE TITLE
Add completion counter on small top buttons with ECB

### ISSUE THREAD

**Issue by Calmcat5** [antimatter-dimensions/mobile-issues#575]
As it stands, completion number is only shown with large top buttons, aligning with web. Small top buttons only show "Complete the challenge". I believe should be changed to "X completions" such that the number is visible.

**Comment by Calmcat5** [comment]
![Screenshot_20230316-101948](https://user-images.githubusercontent.com/94936969/225646259-c830991d-3bcf-4c04-90e3-54133672dd20.png)
(how it is currently)

**Comment by kajfik** [comment]
Implemented in 2.111.0i18
