### ISSUE TITLE
show cel7 time estimate after armageddon somewhere

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#578]
Title

possible solution:
![image](https://user-images.githubusercontent.com/66326188/226637604-52a3be6a-377d-4dde-ab81-214c166f7304.png)

discord convo:
https://discord.com/channels/351476683016241162/1077957647296372756/1087740177184727090

**Comment by kajfik** [comment]
Added in 2.111.0i14
