### ISSUE TITLE
Automator while total tt gets stuck in one instance

### ISSUE THREAD

**Issue by Calmcat5** [antimatter-dimensions/mobile-issues#579]
**Describe the bug**
this specific while loop does not terminate even after the condition is false

**To Reproduce**
1. import save
2. restart reality and let the automator script run
2a. the script is not perfect and may need the ocassional manual eternity or infinity, sorry
3. observe behavior at lines 164 and 165

**Expected behavior**
the loop is exited at 14000 total tt

**Screenshots**
![Screenshot_20230322-081738](https://user-images.githubusercontent.com/94936969/226917121-dce32937-d472-40aa-b1c4-272384c6bdbc.png)

the lines in question

**Savefile**
``AntimatterDimensionsAndroidSaveFormatAAAH4sIAAAAAAAAAO1dW3PbRrL0bKyo9M6y5X0cImy4rjqmijI8m7D47rFExCItYkwEOCtrRe0cffTPYPLDACRkC0ale0brYjmJhAHR0c0a9PT0az2XxtfjZLbI0as0cpKs3L7fHP75mUk6f0bUDkh0cu0bHyXGSl9kqKct0ac0czz10bP0abl3kQPr4Z0aqI0aYJyPjle4TPbbQKFU2Utgb9SccOI1g9AYFcW0bCoAu85WSMZIq6daMEIkldZqPemgLje7FDnn2SJbJmVW5EhgtVuW2XqZIQk5Oc62J7My0b5z6x5HRdpbm20brhZbItr7PZp0bOfyZQMPPwxuz3d7PLZwkFbFTusU1Q0c3q0aa5QxeXBVzoMImxyAW0bEVO6eT47tfsdpFuuxQYiQkQeH1W4GOcaWUcrhwE0bzlZOnliwaO4b5Ll1gFfJrNPvxbL9KL4gpJ40c7VXuV4JNOM82Xw6d834Olttx0ahoXon0b3fp2k8zTrWPVvsSmgglpCFeWKqONPqMDVP6EN7By2epVUXj5f9zdnyd3bxu5usrdJsvkLsM6GBBxtsrK19Ur20aqyVfE7aK3lm0bbp6tYquQueF3UrMqkOtGFdAeEa0cLEqI36vuV7IH3dLeFdS5tvlXb4sZp0cSed0avvAYioU2azO0bvC0c9Ag9aDQ5ZkLDwh98D7AehPAmSEpT8A0cQD0aHwHImdVt8nGZnhZgFPPdbtWwSmc1qHRWjemORbo0bhzG6uQcA8qy8f2yEjUZH4kbHzuBKkegjgysZGFx7htXZ0cftHhwVn8oesfVumSWPtiTg0aZI9r6ePb5f16cQJu0aekyTfKGrys0bLZbLZL1N49KrYoN1Blqr5DbLk819NCofdAD0b0a0ao0boBhvMtQO744MuhaCa0cM0aR0bHHG80c0aBjZQ1JnB5iyrvuw0a0andf113RIq32dO1u36w92Yrkn6HJH5AbhA4zBLXXodVWUfskST79jcOy3yazTXaTzdJu3HPAfvZMzTbLb3fLZFM1Xe90bCbC26xRHma97xpwDgw4d7QfvN4xo9cEe1Nyry0acaShtD1VMbSvP0cnDcGw66Xf0bCDF0bz1Ii0a2qQ8FO0a9glJnkoAZvvY12A2E80bMb92woJMb9mSoeRNb5F3PWZ9wR8AEaDGNa1bIK8Xai5xVHWzQYElgL8kN2mE4kqqNXcUa0bVLrq3XiQ4glroZpRPBan0bQOC2xqC5fdZOjneRyqP4IjxyBBri0adAhNKRBw6hQclpBkVz30aZAemg0bBrNBhuEh220cTcd8rg1t0cS28RjdB5TO0aWAj9e9KS69dg4Wm3LLoV8aK4WynEintB83yaf2Nej4nypFuL9MwY9CnxD7pJnoCcUpouiRqjqvMgyVJQWYsxSeLzOQntOimxswR7fOKYQancz0cuduWb3BI0bUcKjl470ceMdnxko6VVaggN6615vhpxttlov0a7Obm3RWnnrnEkrL0b7VX1mp2xPHDJxYFWFN3xwkd0ctc0aqCtYubEuLIGg0cKOfVAhLof6UtGNY2uHvrx3qDjMSMSI9JiRmgNZ840bz29QJoLYql10cctkg6L4Lla9IPVrf2ssMZ1GShy2it8e9Ergn8D0bYyodsSUdBmSmBkZYPSU6l0c6kb2eJuxJYNPer4a6qnrBjVA6QfG8vE2yfOiO0a85l0bjldjpdKHwjpgyCDAMijzJ8iKd0cpB0aSEA0aIoAryOZYUlGNBF0cQQLzy7GC6BhQyIWpEuetKSfUr3XwWRxr4r1dObr69aSV0aU0bSgyIde5fX90bmea0b0aldeImofcyR7OpMeVdDg0bRSBnra3tyaOyw25UWLihuA7u0cY3NqltS0bf1xYTBx3711U2xui7IMRFfdCKc7O9SCxYaxou1XhESVIN0aKkGHwZAg4GQRNBgE0czWY14dSAvXL3ehamiZhuuzMWVfmm0bEJjQ0baKX10bHLTfKTvUAkAHmpM0bY9Jk0bRSqnu83WhyI9oczcrV7NffGAQvkbQXgTlT0cFaHU5kyGuZIAjCbk9SQzFap3kjxmyWX0aXfEaIEtfe4jXxWHXzSTUcpEg61MbX4KGe47reJNvFee2x3UZOHthEt4SCs4bVv0aGUgNc44OFvbqoAhr6rRbKZdyKRgRgYYo9GHN6d9r4o3oP2WiafvYqh93lVAnbsi80abzhtremcg1SXAa9XoJl2WZ838ZjhV9yvEANs34Ix7ES7gsuLvL3wAfbEpbkFi2zZEAzSX4CgnGLG3DtgWEQ6WRKjXFbmGUyiELVZyXnHyF79sMKhxrTy1ti71JHHwBVIpPhIGJejyg7P0cr3RTYB29L0bFFvkyyMl0amrlGTzaezPN3c3lcM24XHgy3XPupnnlwwM89ubrIZXN9fuxkQ0alsua9Z9t49EhLVr0cfpsoOw8KkO34yrLZ0blvEEO0cW80b9v4o4Rs1gu0cDxB5z0cI3A0boEEoN8W61tUboAOh6qnv7q50ccNXOZZ0auUozNzzOMZ4Fq3XtxeXi8lkdds5meyxpqwZTdabJ0bm89gRN1WNQ7u4ZKAMwzoXG7XywSC822x28yq8HhRfDltzRaWwAu0cb0bZVH8Kr4AWcfFtk237N4cY6XS5TP0a74tQlnPvtOSHYTrKbvmoaqR6F5UawCC0bpd3zcp2IoErI8j6S0cS0bZtwsK2mT0agwK3oSz8jAeJuX0aTvtNErNvW8hvY0afO6iEEx9k0avvrJphhIPSkyqJMliePbJwZoO6er4eTiyLLy8OI3Dt15D0cqHVeNVZ64J52qVU0aGLbtIiq3fpBNJ9iZbLg8iWaegQ3mZ3KZXa0c0bMo53Od7N0afl3UCwDzdJbcvzCPdQJKV9y9MBdoafDrKv0csBfl8TmZu1fUFmTyEPfX9B0bfiOYbL2SJd3fvxtTKm1fu151D1rB0c3f9z0cC0b0bD4QXjtblN541lh0bHQFzX9ZeF3EFymYC1dtP0c3ZLlLw3mZinozOV1toajnVd3l2k8pVzCCOUdXUgb0b8KpAJrtV4yNjb0aw0bvUmaKS0cqy8p0cZOXiMsWBNZ0a1YReUd6fKZ4td0cilyfqrAnAK3dAURQeuN4OX9Kb4QFwWvd0aKh56cOY1m6TV6G9ueXIHsgcGzr8xEU6eT8Ki19OISXl7v85PzgAjh6kJcp6AE4OOc485R3l9WGjfinq0aWxDr2OD6iKOzDkJ1HH2IPeSezquh4HwPkqkuUljgSoc1dluh50aaz7EVOF3t0a6Dz0aLVH0cnPv3RZO0aPvf3LbkQ780bJfeNXHmEJSoUpPjL0bjH0cLLM1utmtezB2QLoSvmtn0bYONiDNGs8W6ctJ0bJfBD624wMi0baaYDZ0bZtu0avFhy0aX4DCjQ7r9Lb2Bp6R0c7LLZXNC5L5yt0bJ9dtnF2p0aHfOqhu2T5YwEGFQrvhYHIQD1PN0cyT8T5L6N30cJnPSaGYp63Y3EVclmrJr0coVzgpfDRtAmhGICSF5tVsuwCafm1aLSKy2SMUHlc7ALnBQ90ajRnvPfUTG3jMXKPTexVujthP117X0a3GnxbZ8tVutq7m6WFyG2kheD8H25wH36yO0a7y0bbNG1DDsqqF8CzqtdYGmC2u0aOeUUkU0cGeYRZHfRKSY8KYCp9werd5Pvn55elcGM20bPMpVTzikTXAkKf6Vl3YhGQR9gTU0cblru5w0cKe4mYBsFX3oPgJxJuzZW8rQMiHTd1s3S5cAlY83OBc76Hm1HI17czlfI0aOG0bBG6GJ3u3CzhNY4jY4acSjIN9wSphTt6IJQyhrNpLaMCCvdTERAXLJRxDU1WnEbidZOicU0cQmopJOG8S5uPow0a1lIRqGtNmyhgGTUcIZYqzLm2vtgdpCw1ErI40aSE8Vo0axKKIabhmrRIW7sOOIchKoNYTFwbhjlioLcNTO0aK3Bj5CjajGtNlWIxcKKNkIYTTqWUgnZpaz6KNoUqw0bsm7icKwGoqGOFEcW26tKUe15hxp8D3HsI9j165wYrUIzhFo0bC2XlS8SL21KiJLNPTgoa113X1bg1pAmGAyri7jxEAjMUu5rdUrgGWEImoUKvmtqKCzGh5ppphKLgXX0agjDlLA9VIoLKUahGhhDxqGilkF3Dt82U2qFAKWz3BBjuO7BQo58DCw5MFKNhAWdQUWiVlPoZQYb0aaCB6AuLc8NHCevbUTnjEmu8FlYQaS0a0aoaB9UExyPUpU6ptBgYaI7vktAMMMmnsNBq0bv7YwwO0arbv11UzIJJ64yYQkPPVGBwEF4PFFgGOkpU0bptBKW1V0cC7aBHBPrFJcGvpQbxmMxmRqLR3CQhWnsZGhkuIhP6gldCuDvsfwOBIbETO1lHADJprhTHRsiik1ZpC57NpHrimeRVTg9Ggh3AbFYTMkOm6aRbNINFOUEKUi7kaNYi6mgjMOvgUMJVJpYx0chLbWOWUsOHcTCj4Rqxg4FGMtHWJNYrbgQwNcCDaKtpPKxesfGpMNtUNmgSgOqNnoBaD0ctwb71PLQ5GToy8ky0av0aMmOOnqD860a8xGS8ng9PHJDOy3NJMNQghPwW8RDe0b5maFGAgmLF3hSHdzmRFPTcnW0bt334XO0cHhGUpFZTOnhmHkKyea60aW2fd1sZzSNt9PD3wEAsSq4ihCcBIHwEHSJgzKP9VVAx4YxRnMJFKyMKHzpLrxo7IidMUGA2BgMURAdKaGD96PqU0a4JuuZZr5mMM87ZFqf2zvJ2dWsZrEhSMLB4Kgtsv3dlR60aJ5ekXJwD897926S69KLaZD0ahxh3OC0a0cvLDJ1QWi0aGXaW45wDMHDDZbXHT7fZv8PLpMnOTKowC1WJdtrEWhlr1VXAeut6S1cyedE6AVJvze2FhfQx7VxYQWqab7e95M0bxA2QqX0bc40bp1XDwjvJ5vf8MqbalG7LBI88VccQkruzvPRTegx7MQgFnvgl2wTbc92GwjJZra0cv19WSJoT5q2Tb0aC6gbTdBnRO4uE3n86LB2WxVBgBpw76ZVDq7y1p0bTemVh9rZHjggx3CbCM4YJbM0a3uzcTmwEpe0cyeVEXLJLNNjw5Ntgy1WVUheBASb0ai6nfopHflabEsNo2UFino9qYpb12HRTZPmxXlk3bn3GXxpX25KD0bl980al6u6v2XwebAHMQVO9eI6vZhm8jqiOEfR2nc7e5mVxsSnKdFZG0b3TLzf1p3TSd4nbCr14NXhRfTpbL5kaDBm0cgToHrNL0cc5duLDdK7Tat5sWbdGjvtpeu4slpSLJtzEG4XDQyt0aKWjO95godMCQ2593ADcBHH2U3Vgczl0ajKLjCT4ETfm17TP0bpeakJbj7U6sttzCsEyEV47gHC7dt0be0awoOalI388d0bsdR0bV0cZ8nRHztC0bPyI0agljE84mYCQknSg60aWxi2MSyCYUYnsJ9yuAHfDgK3gy4bhMYGSY4MQG2C0b7ADSgHM0aoV0bzf5I294lPt48An4LRZeIvx7eCT7eNCJoRPwSWE40bb56gFF0ckapMgHDMKnsqK0cgXaUFk80aRWyYFafbvwkFXAKF1j9PJi8pvAUA3leA90c50cCvABbwA0awYwx8Dv4sIEQwfISCPiSIsIAzkG3DAYxw0bBAMYa0aDgmUwY6fQlh7JG5gTBAsQOJfwO10axF8o0cabQfDyUtij0bBEnL0bZcSSEcYrVEaeXHO9IzovYQ0aapSbjfwEfof0bRoMo9qD0b6IpoIc3R1Vjmp1tx6N4S4Pb35JsrK52adEWUTqyyJbgpDQ6zoqSy0bn2RGV5OjrH0cnRUTWBfpQXjiwalT0cyB0aTYsPfjXRdUcXPzR57dVJSDNauahao4wDPpjA49If0aDLQg0a0c3UJjFj4nr0cs1lFGVcQnHPp1ms0bz0cLbPK63UQ0cqHe1U7OnrA0czVw2RBc3odbduCyYbjsG0bHykXD5SOkmHbh8GC59Uel2VRFiwscF20b0aIoovsgPY34GOuKXLdj3ZA230aVvMjlN4pc0cjUKrb6x0c6nnVejv6n8DcEf2v5eVbqNaNVDB9AGN3q0bwB5U0bpOp8mj7hSmEf0aX5A0bA3aP8ihaTMz1GZDXTtrINfNZp7SKAf6bYNHjNWhPh7xEjqtR1uMHh798lZY80aGdjbUr0aMlHxoiuogHZfTrVCMeO7vA94diXF47Rg0aPUo8JRo2QDVJ0ccCVuHigxJjI5SJ0apivoeqj9MENeFuVQdGgkGHM6Qx4HX6WMzffhji1NizJzad3YNdj8RuD2GHqC2CPoDxkfpE0aNdNM7b82obE0bMqX0bW1QR0cX0a3Wie2GtHVpmKl6tzWKmmTl434yqtMfvDEduONLDDXWLAiATgu13ieU0a0bHRv2DCGiL4JorGc1hIg9AdFYQINew7hR0bklewwg8O0ayoeZSu4xcxNG0b7QsSseRR0bCzVWdjS24TLAvdcV0bh0ah7AY9Cg0cNZELczXq0b2nGT0bSVPcH38GPOHlst0afuyyOJVuGvnrcTrPymJz5SZp3dM3xXJZfDm7S2c7PxnuZ6hvis0as7a591CnxNm7vcHCqM8EMP27Cd7VK8vlVzS2pdgR0c9IuVNaE5LgHhZrxllqd0c260a0b4mQyY7i2OZ4C1V0aKVFqXcygsUsJtGSjWv0bGe7Kbe7lxwAg0cOcQnjJEr5G66NRCeR3tdHoHGlS1eJfxguxs3vjn0cm7b5vUh9PhlI7ZT4XDDRJkxUCYTakOGemajxW0aWINLduSonaqGlJhppGImpBGS1bRsxU92mJjLUEp3GkBT9CvUkakcOXXVZFXZNqt7SwgI8Iquj2n7ijExm0avrxbV3kQJG7Ic196KzX0asU0aYUlUZwwohptNkxltGm0bpoxKAaRQnNFtDCCaAaN0akqoPboeVUpJyeumq6jrtlotcUb2CyegIyo6qqHDIzpiJJ1azGKQjtlPRxBbkXHJvlyr0ayE14nTKG0aJNvp644a1SdRPougkaWjJQSR40a0cQAoxonwZEyt2a1qq5aOCur2qGbTqn61UovB6lET9JLhDkcZM7WC1TKngYYFKqZ0aUMFhYYmKlKxhsaHm40cwgLGmsYZW4VM8QBFIXKmjBoX4bNB9VfRMQ1I8pTBq0bhxStyNQ6zumwmQt7i7cBkR5IRSpCjSIMAwKB28Oq4HJY1xT7BjhQByb3y6puPdo0aHxmsIHRjc6D9WmVndQ9kAbGgASUfo0b0bhPrDaVgUmOECn5FSOasa6N0cMAmAiAyUAdGlO0brpfB0cfo6cWv433dkrVpaHnGAbef2HLjzoLjs7wYSn2pte5HkWAHvEWTnp8m6Zl2npm0aPN8Xll4fPUAfP9s0cMdHPftjdwbd7tf5njwRFKQSmY0czJB8dmD30c6eV0csKwq0aZuILf5CbsHKD4ica7EaE3UcoVN9WegKtstXMHPpoDfptPI49u46NeBriiBbqPa2GEuCU1NoEuBhoj0bUTwidQTTSZSTqTAdTWNK2wS3sK1MA40cAn7kh6Zth40bV8Xg7pnUuXHT8g0a0bqvx0cqjRitm5nOinz0bBrzlbYY7Tqjf20bASFfTljVss3nS2sgTbMq5Alz4mm0aqFSOekCKbPlE1ZTwPc7YfonL0a7fNfumMDL7rEZf7Yjqj9njHHNrAbnxbiMle49f6Tvefrv5P0bB0a1offjxfZfmeTaV0aijumKQidWyE5SP4hePGH0aJ8sdBci0cdZGBO31D2F0bmzAvIzfIjWnN0bd4qtVFzjZa2yp1KlRZQZeISkKTzw9L0cJuH3fKVh2Y9wlZ5X9oPe4GBwMOQNNicKxJRD8Glg0cCA4my3VmXazBKv0a1MeyXtgUIjYmiFHCSIMDsNvGF0bYVfv0b1OsA5u30bTdC1Sd388uIIKRk4mFIwpWrpjmOtwP2CfBI0cfNwq39FNhLVEgCP4QqgYl1MrWp6ou3UzL4xBFvDNbTAXhUnGAhyf0a1DND1FSxFqG0cOgCQM9VlYKU2aN4txaNaz4vQEBH4pf7qAEIWI4QqUUW1BeXSTIGPop8XIeZMbhH6qwMIaXwCT0a8lmDDw5ZiFTmBwKu1ZG1mQQA391QGAhIkYIGNSCK0aAHnQ90bswSpBRMeNBR0cOV0biCJGyKdWgSUG0c8IQro15ZoQM4voWoL0caj0a9SEyuh4XjCWFGwXlrQ5wYIMUmghP5qP0aAbC1BOtQTjg6nruaSW0amcWoGUmUMLqcj9CI1V8zoNAiME1xdhcWv3MhgbCOhZaa30cpYnA0czIRp8PcOMwNngA7gHHgjADbVVivLKRdGMU6lPuM4xVTuubtfsD8A0cgD4A0bAPgD8A0cvUA20cHlsj0ae9P5rL77f4wl1jjobXM39roq4c8PSKuFymlgq9JkOvnRKJWeYmUFyYfWZW0ceN0aJJ9aKMhGULMMY7GXrDgFuDHS6TyYLlpsZqpocxqiJ8YPGOF6YOl48FS9NK0cX0aUEUUYyh9UA8BYtm0aqtLQhX4ieNCHiLZ6YHV46Gq6fie9HaqYBwBhq60bnBOAFZMLR6IN1YScMg4GdADuldrO66ZJd0brB0bBUa415sNwfxVkrV6EIA3cPvVoixYBU6ROQCvW9vaudMWosg4ECCuGBdvo6BFGMhijxo8rfiRHCL4Kz41oqJUnQpTj2NojCMUsRGACmhxp0bvDjZVH23tZKKcqNp1fBUBRaXEMMgbBWUQM0ci1AzI9Sn9f8zcxn6omNTBaq1qw9oKFqwLlWAPCAeraoWiQ0arwJLAjIsz9HWoqIBjUhHvBMh2ChQAT4kXo0bIoZIRiaqmBa9HWV5Bm0ahRKKi0aUQuTE0aEu0azF8vkHp9pPgpnVPAxPExD3WbWrxd1emsMVMZJvjD1GLcGt5Ux4MeFbBZ24N20cJ8ve650aJQaYUvm8IWAsww7x60cW2f9cCKXvMk5vMsduV5cncyIkWve60aJLi0cSzfnhxcPgnfvLwGDb9s8Z9sPwuceeWQHMTuLK0aZ91h3ffdtbaxmVoCGyNCmdJ0cdWD14C3nYyIA83guHUypxBjCegtjKIwIPi12ubtng44Ap3MN1Kj3RBWaPjDXe46TOXwalfJ0aIDSVynfv1lyowTQW9Yc6AGi0awMIuGao0cphdEExNrcLtLPmAhnXS5VjKNWEwVgpimaUxhUoGjLiZY7zxJrRRdeHAiuCAHg9K0aE3zmE6bEG1gWGfCwlBO3QCHCfev9yQVGUiyiCkkLnoCPLgoMKTlUP8424uZMopLm6DgghqlrX0bxTQraWR4lxnTeh5GK4RQmprVjHSUBswauWDDPXF0a0c0bAJvTU0cKV70cWn0bYEJ56AAYPRG4iCOtDKsO5LSg0bKI0aC6pJPzzFjQA8yYCL8ohaJ3VEIrLqbgDlipiSIU0bEoFzB6a0cSVV5QeTmUlhOhEMpqhUCpw1jl69WymeLZJ8lgZfbLRhJhqOC5r0bSwIu5UizL6X0cVUinVM2HndsbjFWSrffJ7PJlk8skSN3qPv7gO0a8wOuXFyWsaJLe4fNNcFPnyPrzpr0a2bgCPM0brqqBoyGUPskXnUyg0cg9JCC5tBLqqvhnFmQjxR2awu8zud6k6etNcnvrvhVB0cCcklul10b5ki6FJK1SrXwqlT0cQrfCbAiUeyJm0aZtbH8U0bAYWV0chh1K86z1WdSlQoV6vzoFL974rnRbii1xSG869NYZ1od359HZReb7Jk3mb8WBaYJ0bbVr8d1svvu7pZarvOD9mqbzjZpGW9afs0bknFQ0cH0bpHmizGX48XbH2R3Kbb39dp7jweYjUeej0c0bnKVfrtzT11ftt3oXxReXmSRWslqja2UZyPlSmYKhb1n0ak7tpI6ni3EJntVQ91IlzdvPqQ0b2vqkRX4OgrzEzVXFO3rTG4xmxG4GfepOCYzi0bS0am0ccbjK6onwm1E1zoOLyyitNqzwl1Y55MORBxtnjl0avQ4DIH9JM0acJ9iwKWUEFUKiSq9gMuKwFyagThBg1sJr0cDDqPLn4vdQq8wHLjuCavNJBJkwHs3D0aMF0cSukTa9DP6TCQl0bSxGgzkdgjyOfwbwMTg2HeLFxjDo2Dm9oALtYAHmiAq8epKE8S0cAVAA8O3rJ8IblW3Hw4vb6eSpnJ6QeQM5xXmf0c7o0aKRHuKGeK0a5JazxXuIPGfsN47ywAO0bUPrtsw0b1daLKUTUlr9x51IwSZzL6LaDgeVdvvbfT64Gi89p9dEXgAlDLBD0bXzf0cd5xuiwAAEndOfSavefile``

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
