### ISSUE TITLE
Imagimary Upgrade texts get cropped on narrow phones

### ISSUE THREAD

**Issue by neoiw** [antimatter-dimensions/mobile-issues#580]
**Describe the bug**
Imagimary Upgrade texts get clipped if phone is narrow.

**To Reproduce**

1. Have a narrow phone

**Expected behavior**
The box's height should be extended so that all the texts fit in.

**Screenshots**
![image](https://user-images.githubusercontent.com/45356936/227709928-18e18789-5d28-4734-8901-48c30c2c8ac1.png)

**Additional context**
Happened on my Z Fold 3, outside screen.

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
