### ISSUE TITLE
TTF working in Cel 7 (unintended)

### ISSUE THREAD

**Issue by shadoweviI** [antimatter-dimensions/mobile-issues#581]
**Describe the bug**
It's nice that it does, but it's not supposed to work since it doesn't work in web

**To Reproduce**
1. Go to the study tree
2. Purchase any study 
3. Resources don't go down

**Expected behavior**
Resources are supposed to go away

**Screenshots**

**Savefile**
If applicable, add a pastebin link with a savefile.

**Additional context**

**Comment by kajfik** [comment]
Fixed in 2.111.0i14
