### ISSUE TITLE
Respeccing Time Studies after unlocking Dilation gives 5000 free Time Theorems 

### ISSUE THREAD

**Issue by neoiw** [antimatter-dimensions/mobile-issues#584]
**Describe the bug**
Respeccing Time Studies after unlocking Dilation gives 5000 free Time Theorems 

**To Reproduce**
1. Unlock Dilation 
2. Respec the tree 
3. Total TT you have will increase by 5000

**Expected behavior**
You are not supposed to get free 5000 TT's

**Screenshots**

https://user-images.githubusercontent.com/45356936/230574046-d2b531e9-549a-4a8f-a8d8-18a9570ea53a.mp4

**Savefile**
https://paste.ee/p/XR3Vg

**Additional context**
This can be multiple times, so one can just farm TT endlessly 

https://user-images.githubusercontent.com/45356936/230574193-a55b417a-f407-472a-a5e8-3bac34e82348.mp4

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
