### ISSUE TITLE
Improvement to hiding tabs (for challenge and options)

### ISSUE THREAD

**Issue by OhBrod** [antimatter-dimensions/mobile-issues#585]
Hiding the challenge tabs doesn't actually hide it until you've completed all of them resulting in the tab flashing rapidly when you reality often.
You mentionned hiding it for good once automator is unlocked. I think that would be a good solution.

As for the options tab, we can't hide it at all but given that we can access it from the side menu I don't think preventing it from being hidden is really needed.

**Comment by kajfik** [comment]
Comment from Lars:
> Perhaps an option to generally force all hidden tabs to be and stay hidden? (Defaults to false.)

**Comment by kajfik** [comment]
> but given that we can access it from the side menu I don't think preventing it from being hidden is really needed

what if you disable the side menu 🤔

**Comment by kajfik** [comment]
Implemented in 2.111.0i18
