### ISSUE TITLE
Add RM gained, Realities, and glyphs gained to while you where gone.

### ISSUE THREAD

**Issue by Reaxt** [antimatter-dimensions/mobile-issues#587]
**Is your feature request related to a problem? Please describe.**
When letting the game run automatically for a bit, if I have auto reality set, I don't know exactly what my changes are when reopening. I also don't know how many glyphs I actually got (or lost from a full inventory)

**Describe the solution you'd like**
Add RM gained, glyphs gained, and realities gained to the "while you where away" screen.
(Also, it may be nice to have something like "Gained X glyphs (Y lost to full inventory)", but that is much less important)

**Comment by kajfik** [comment]
Added in 2.111.0i18
