### ISSUE TITLE
Black hole potentially unexpectedly charges after leaving EC12 

### ISSUE THREAD

**Issue by Reaxt** [antimatter-dimensions/mobile-issues#589]
**Describe the bug**
Entering EC12 and attempting to charge the black hole shows no indication of anything happening, but upon leaving EC12 the black hole will be charging.

**To Reproduce**
1. Enter EC12,
2. Click "Charge Black Hole" once
3. Exit EC12 or time out on EC12

**Expected behavior**
Given no indication is shown that the black hole will charge, it probably shouldnt set the state in the first place.

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
