### ISSUE TITLE
Glyphs rejected by filtering do not increase glyph sacrifice total values

### ISSUE THREAD

**Issue by msiitan** [antimatter-dimensions/mobile-issues#590]
**Describe the bug**
When the glyph filters reject all glyph choices upon Reality, the glyph chosen by the filter should be automatically sacrificed, increasing the corresponding glyph sacrifice total value. This does not seem to be working. 

**To Reproduce**
1. Load the save file
2. Set the glyph filter mode to "Lowest Total Glyph Sacrifice" (or any other mode which would reject all glyph choices, but the Lowest Total Glyph Sacrifice is easiest to observe, since you only have to watch the lowest total)
3. Observe that the glyph sacrifice totals do not change upon Reality. 

**Expected behavior**
Total Glyph Sacrifice values should increase with each rejected glyph upon Reality.

**Savefile**
https://paste.ee/p/iT0rf

**Additional context**
The sacrifice values of the glyphs produced in the above savefile are around 1e133, while the totals are at around 1e135. Thus, each rejected glyph should increase the 2nd significant decimal digit of the mantissa in the total values. In the state of the savefile, the filter has been set to the mode which accepts glyphs with at least 2 effects, and automatic purging has been turned on. This is the only way I found for automating the Glyph Sacrifice Totals farming.

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
