### ISSUE TITLE
Export to web creates not a valid save

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#591]
**Describe the bug**
Export to web creates not a valid save.

**To Reproduce**
1. Import the attached save
2. Export to web 
3. Import the save on web version 
4. See poopoo
5. Delete `notify "blob"` from tomato and try again
6. Now it's valid

**Screenshots**
![Screenshot_20230426-234128_Antimatter Dimensions~2](https://user-images.githubusercontent.com/56225774/234647554-b715d3e7-2075-4d41-a97e-31805622273f.png)
![Screenshot_20230426-234218_Chrome~2](https://user-images.githubusercontent.com/56225774/234647585-8dfff8e1-af92-440e-863f-c4d7b692cc44.png)

**Savefile**
[not a valid save.txt](https://github.com/antimatter-dimensions/mobile-issues/files/11335439/not.a.valid.save.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
