### ISSUE TITLE
Tomato's line breaks converted to `\n` in web save

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#592]
**Describe the bug**
All line breaks in tomato will be converted to `\n` in export-to-web save.

**To Reproduce**
1. Import the attached save 
2. Export to web 
3. Import the save on web version 
4. See poopoo

**Screenshots**
![Screenshot_20230426-234352_Antimatter Dimensions~2](https://user-images.githubusercontent.com/56225774/234649556-08b44611-3166-4b97-b7fc-4c9f95e114fc.png)
![Screenshot_20230426-234448_Chrome~2](https://user-images.githubusercontent.com/56225774/234649587-443404cd-645b-4e4c-896b-d4a0b5e93f5c.png)

**Savefile**
[line break.txt](https://github.com/antimatter-dimensions/mobile-issues/files/11335494/line.break.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
