### ISSUE TITLE
inconsistent glyph filter text

### ISSUE THREAD

**Issue by Calmcat5** [antimatter-dimensions/mobile-issues#593]
glyph filter's specified effect mode has inconsistent wording on the first effects for power, infinity, and time glyphs. screenshots for info

![Screenshot_20230425-135326](https://user-images.githubusercontent.com/94936969/234984838-0a6bee12-c7de-462f-8f5c-21638804deac.png)
![Screenshot_20230425-135345](https://user-images.githubusercontent.com/94936969/234984860-c759dfb5-b90a-484c-b4f3-83a5a4c36c7f.png)
![Uploading Screenshot_20230425-135357.png…]()

**Comment by kajfik** [comment]
Seems like this bug is also present in the web version of the game.

**Comment by kajfik** [comment]
Could you please submit it in #web-bugs too?

**Comment by kajfik** [comment]
Fixed in 2.111.0i17
