### ISSUE TITLE
Strike through of hidden tabs are not visible

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#596]
**Describe the bug**
Strike through of hidden tabs are not visible.

**To Reproduce**
1. Hide tab
2. See there is no strike through 

**Expected behavior**
Show strike through or another way to indicate hidden tabs.

**Screenshots**
(I hid the infinity tab and autobuyer subtab, but there's no strike through)
![Screenshot_20230516-214043_Antimatter Dimensions~2](https://github.com/antimatter-dimensions/mobile-issues/assets/56225774/a215fda1-cb09-4221-b9c6-6715a89d02d9)

**Comment by kajfik** [comment]
Fixed in 2.111.0i19
