### ISSUE TITLE
Total Termination Bug

### ISSUE THREAD

**Issue by tayloreeves** [antimatter-dimensions/mobile-issues#598]
**Describe the bug**
When you initially buy Total Termination, the glyph sac menu does not auto update to have the correct effect values. It does correct when you reality/sac again

**To Reproduce**
1. Have less than 1e100 sac
2. Buy total termination
3. go to glyph sac menu
4. sac totals will be correct, effects will not be

**Expected behavior**
I have no idea if this can fixed, but it could be nice to auto update I guess.

**Screenshots**
![Screenshot_20230522-202630_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/134403574/73531bb0-88df-4b9a-95ce-2ed67b70a781)
![Screenshot_20230522-202626_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/134403574/f1ec0f93-6383-44e5-aa5d-2f270c7cfda5)

**Savefile**
If applicable, add a pastebin link with a savefile.

**Additional context**

**Comment by kajfik** [comment]
Fixed in 2.111.0i19
