### ISSUE TITLE
Rep Glyph DT Gain in Pelle

### ISSUE THREAD

**Issue by tayloreeves** [antimatter-dimensions/mobile-issues#599]
**Describe the bug**
In Pelle, when a rep glyph is equipped, in the rep screen it still shows the DT gain effect being present

**To Reproduce**
1. Enter Pelle 
2. Equip Rep glyph
3. Go to rep screen
4. See DT gain effect

**Expected behavior**
Well its not supposed to be there lol

**Screenshots**
![Uploading Screenshot_20230525-095931_Antimatter Dimensions.jpg…]()

**Savefile**
If applicable, add a pastebin link with a savefile.

**Additional context**

**Comment by kajfik** [comment]
Fixed in 2.111.0i20
