### ISSUE TITLE
Big Crunch screen can cause a hardlock

### ISSUE THREAD

**Issue by JohanniklasLp** [antimatter-dimensions/mobile-issues#600]
**Describe the bug**
The Big Crunch screen that blocks most UI elements and prevents you from interacting with anything can cause a hardlock.

**To Reproduce**
Prerequisites:
- You cannot have bought "Existentially Prolong"
- You must have bought "The eternal flow"
- "Parity of Singularity" is highly recommended
- I don't know if any other reality upgrades or perks are required
- Your Black holes must have a sufficiently high multiplier (in the attached save, BH1 has e6, BH2 has e4)
- You need a glyph with "generate TT" effect
- If you want to not be permanently stuck, make sure your black hole 1 is not permanently active and has a high enough inactive time for you to deactivate the bhs or the autobuyers
- Make sure the automator does not mess with the reproduction steps

1. Disable your eternity autobuyer
2. Start a new reality (unequip glyphs)
3. Equip a glyph with the "generate TT" effect
4. Buy all studies up to TS181 (Idle Path)
5. Wait until you have the eternity autobuyer unlocked
6. Eternity
7. Make sure all normal challenge autobuyers are running
8. Big Crunch
9. There may be an unrelated bug where you still cannot see the UI again after Crushing, if that happens while in the autobuyer tab, just restart your game.
10. Set the eternity autobuyer to 0ep
11. Activate the eternity autobuyer
12. Wait for black hole 1 to activate if it isn't already
13. Try to do anything. With a low enough BH1 multiplier, you should barely be able to do stuff inbetween crunch popups
14. Wait for black hole 2 to activate
15. You should be pretty much hardlocked now until the Black holes deactivate again, especially with high BH multipliers
16. If both bhs were permanently active, you would have no way of getting out of this situation.

**Screenshots**
![Screenshot_20230528-130005_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/e177fba8-bd15-41aa-a9df-494b2104a292)

**Expected behavior**
For the fullscreen "Big Crunch" screen blocking all Interactions to no longer appear at that point in progression

**Savefile**
https://paste.ee/p/0umtS
This save is in a post step 11 state

**Additional context**
BH1 is active for 11.09m and inactive for 58.37s, BH2 is active for 2.09m and inactive for 22.27s
When loading the save, you might be unable to do anything until BH1 runs out, but you definitely cannot do anything until BH2 runs out

**Comment by JohanniklasLp** [comment]
https://discord.com/channels/351476683016241162/554713718282256391/1113402808092344350

"The Big "Big Crunch" screen covering most of the UI and blocking interactions should be disabled after the first reality reset, second at most"

**Comment by kajfik** [comment]
Fixed in 2.111.0i22
