### ISSUE TITLE
Celestials Reality Popup

### ISSUE THREAD

**Issue by JohanniklasLp** [antimatter-dimensions/mobile-issues#605]
**Describe the bug**
The popups when starting or exiting Celestials are borked.
When entering a Celestial, the popup says "You are about to **exit** [Celestial]'s Reality. Perform a Reality reset, and enter [Celestial]'s Reality."
When in a Celestial and clicking on another Celestial to enter their reality, the popup says "You are about to exit [**Celestial you clicked on**, not necessarily the Celestial whose reality you are currently in]'s Reality. This will place you back into a regular Reality without any restrictions."

**To Reproduce**
1. Start a Celestial

**Expected behavior**
For the text to be fixed ("enter" instead of "exit" for the first, and either "exit [Celestial whose Reality you are in]" for the second one (definitely that if you have clicked on the celestial whose reality you are in), or the enter screen for the celestial you clicked on (if not the same as whose Reality you are in).

**Screenshots**
Entering Effarig:
![Screenshot_20230610-131125_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/6acdd148-535c-4b17-aca3-5cfaa4842c8e)

Clicking on Nameless while in Effarig:
![Screenshot_20230610-131136_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/3792e064-5c3c-4f44-8a48-7ec0a9cddb67)

**Additional context**
Only tested up to Nameless/Enslaved (potentially another issue that Nameless and Enslaved are used for the same Celestial)

**Comment by JohanniklasLp** [comment]
Related: Exiting a Celestials Reality via their reality symbol starts the same reality again

**Comment by kajfik** [comment]
Fixed in 2.111.0i22
