### ISSUE TITLE
Certain Glyph visuals not updating

### ISSUE THREAD

**Issue by JohanniklasLp** [antimatter-dimensions/mobile-issues#606]
**Describe the bug**
The glyphs in the glyph tab are not properly updating (only visually) under certain circumstances until reloading the game:
- When entering/exiting the nameless ones'/effarig's reality
- When gaining a new effect (in the glyphs you can choose from on reality)

**To Reproduce**
Issue 1:
1. Enter The nameless ones'/effarig's reality with a glyph that will be affected by the level cap/increase of the celestials
2. On the Glyph page, the glyphs will still have their old level shown until reloading
3. when clicking on them, it will show the correct level
4. when you have reloaded, the same is true when exiting their reality

Issue 2:
1. Get a Glyph with less than max effects
2. Get enough Glyph Level for it to gain another effect
3. It will only show the new effects after reloading
4. If not reloading, the new effects will not be shown, even when clicking on it
5. when choosing a glyph, you will not get the hidden effects, only the effects already shown

**Expected behavior**
For the UI to update properly and for you to get all the effects a glyph has when choosing it, including the effects not visible due to the bug.

**Screenshots**
For issue 1:
After entering effarig, before reloading:
![Screenshot_20230610-130625_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/54d09e7d-30b4-4996-ac4e-5821c1821563)

After reloading:
![Screenshot_20230610-130726_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/1a95566d-cb6b-4175-85b2-0176b472babb)

After exiting the reality, before reloading:
![Screenshot_20230610-130752_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/207a3a80-714a-4f50-ad2a-2fe390e60d30)

For issue 2:
Before reloading:
![Screenshot_20230610-130859_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/9a69a5ad-c469-4704-93a9-9743f765e777)

After reloading:
![Screenshot_20230610-130906_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/81ada724-81d3-48c8-bd51-3c37dbb0dd30)

**Savefile**
https://paste.ee/p/sb8yt
You will need to unlock dilation, doing so will unlock reality and the glyph selection, reloading after that will show the other effects

**Comment by JohanniklasLp** [comment]
Issue 1 can also be reproduced by (un)equiping a reality glyph

**Comment by kajfik** [comment]
Fixed in 2.111.0i22
