### ISSUE TITLE
Duplicity of Potency not unlocking with 5 glyphs

### ISSUE THREAD

**Issue by JohanniklasLp** [antimatter-dimensions/mobile-issues#607]
**Describe the bug**
Potency of Duplicity (and potentially the upgrade requiring 4 uncommon glyphs) does not get unlocked when realitying with 5 glyphs meeting the requirement.

**To Reproduce**
1. Get 'Synthetic Symbolism' without unlocking 'Potency of Duplicity'
2. Equip 5 Glyphs with 2 or more effects
3. The upgrade will show in yellow, aka as unlockable
4. Reality
5. The upgrade is not unlocked

**Expected behavior**
\>= instead of ==

**Savefile**
https://paste.ee/p/1uXUS

This save has done step 1 and 2 and is ready to reality. (The fact that I have edited the save to have way too many RMs is not important, it certainly helped with step 1 though)

**Comment by kajfik** [comment]
Fixed in 2.111.0i22
