### ISSUE TITLE
Pelle Rift Milestone references wrong Rift

### ISSUE THREAD

**Issue by JohanniklasLp** [antimatter-dimensions/mobile-issues#610]
**Describe the bug**
The first Milestone of the third Pelle Rift references the third Rift instead of the second one.

**To Reproduce**
1. Get the third Pelle Strike

**Expected behavior**
The milestone should reference the second rift instead, since that is what it affects

**Screenshots**
![Screenshot_20230614-074817_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/a949985c-f790-4eb1-bce9-33db3228a992)

Collapse is Rift 2, Disorder is Rift 3

**Comment by kajfik** [comment]
Fixed in 2.111.0i23
