### ISSUE TITLE
break infinity tab unhiding after eternity

### ISSUE THREAD

**Issue by JohanniklasLp** [antimatter-dimensions/mobile-issues#613]
**Describe the bug**
After Eternitying, the Break Infinity tab, when hidden via Options, shows up again as if unhidden via the Options.

**To Reproduce**
1. Hide the break infinity tab via options
2. Eternity
3. The break infinity tab shows up again, but with its symbol instead of just "-"

**Expected behavior**
For the tab to only show up with "-" and to disappear again after buying all upgrades

**Savefile**
https://paste.ee/p/ExRYP

**Additional context**
This issue stops once you get the "Start Eternities with all break infinity upgrades" milestone

**Comment by kajfik** [comment]
Fixed in 2.111.0i25
