### ISSUE TITLE
Milestone/feature UI goes up under text in Cel 5

### ISSUE THREAD

**Issue by NiZeKiHo** [antimatter-dimensions/mobile-issues#614]
The issue is when you level up a cel's memories to hit a new milestone, it bugs upwards

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Go to Cel 5 menu
2. Click on a level up that unlocks a new bonus (but not another Cel's memories)
3. Watch the icons go up under the text

**Expected behavior**
I expected the UI to stay in place

**Screenshots**

https://github.com/antimatter-dimensions/mobile-issues/assets/66221827/085c3033-fea7-4402-a5d6-cbbfd1600b5f

**Savefile**
https://pastebin.com/4vky4qD6

**Comment by kajfik** [comment]
Fixed in 2.111.0i29
