### ISSUE TITLE
Some numbers on the blind notation are not blind.

### ISSUE THREAD

**Issue by HifuminOwO** [antimatter-dimensions/mobile-issues#63]
The achievement multiplier when being on the blind notation is not "blind". 
Also in the description of the achievements some numbers are "blind" and some not. I don't know if they are a different variable and belong with the dimension numbers.

Suggestions : Make the eternity milestone numbers "blind" . Also in C5 the tickspeed percentage is still visible and at the 6th eternity milestone the 25 is visible. At last both " Increase the multiplier for 10 dimensions " infinity upgrades are still visible.

Keep up the great work devs :)

**Comment by kajfik** [comment]
Some numbers are hard-coded and aren't affected by notation.
I changed only the achievement multiplier to be affected by notation in 2.9.4.
