### ISSUE TITLE
Disabled golden button IAP gets re-enabled when you leave and reopen the app

### ISSUE THREAD

**Issue by AEiOuf** [antimatter-dimensions/mobile-issues#630]
**Describe the bug**
Disabled golden button IAP gets re-enabled when you leave and reopen the app.

**To Reproduce**
1. Tick off "Is enabled" box under the "Golden Bottom Buttons" IAP.
2. *Leave and re-open the app.
3. The "Golden Bottom Buttons" IAP suddenly re-enables itself  woa magic

*app does not need to be closed

**Expected behavior**
The IAP stays disabled to be consistent with the other IAPs.

**Comment by kajfik** [comment]
Fixed in 2.111.0i31
