### ISSUE TITLE
Effect of Cel 7 upgrade to increase Glyph level does not apply until restart Reality

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#633]
**Describe the bug**
Effect of the Cel 7 upgrade to increase Glyph level does not apply until restart the Reality (Armageddon) or until restart the app.

**To Reproduce**
1. Import the save for quick reproduction.
2. See current Glyph effects.
3. Buy the upgrade (Increase the Glyph level allowed in Cel 7).
4. See current Glyph effects and compare it with step 2.
5. Restart the Reality or app itself.
6. See current Glyph effects and compare it with step 4.
7. Enjoy your trip and take a good rest :)

**Expected behavior**
The effect applied immediately.

**Screenshots**
https://discord.com/channels/351476683016241162/554713718282256391/1143506628839231598

**Savefile**
[glyph level.txt](https://github.com/antimatter-dimensions/mobile-issues/files/12408173/glyph.level.txt)

**Comment by kajfik** [comment]
Fixed in 2.111.0i35
