### ISSUE TITLE
Time estimation popup for bought Cel 7 upgrades are not necessary

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#634]
**Is your feature request related to a problem? Please describe.**
I think it is not necessary to show time estimation popup for bought Cel 7 upgrades.

**Describe the solution you'd like**
No popup for upgrades that were bought already.

**Additional context**
![image](https://github.com/antimatter-dimensions/mobile-issues/assets/56225774/d67d22ae-07bc-4168-9c44-6c82dbfecf99)

**Comment by kajfik** [comment]
Fixed in 2.111.0i35
