### ISSUE TITLE
Cel 7 upgrade button is slightly off-centered

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#635]
**Describe the bug**
Cel 7 upgrade button is slightly off-centered (size is smaller?) after I buy one on the left side.
(I didn't try to buy on the right side without buying the one on the left...)

**Screenshots**
![image](https://github.com/antimatter-dimensions/mobile-issues/assets/56225774/0f1e7365-fd61-49ca-ba8c-735a45c04428)

**Comment by kajfik** [comment]
Fixed in 2.111.0i35
