### ISSUE TITLE
Crashes when doing fast realities

### ISSUE THREAD

**Issue by Barrin84** [antimatter-dimensions/mobile-issues#638]
**Describe the bug**
When you are doing fast realities for perk points, it crashes if you set it too fast. 

**To Reproduce**
1. Go to load save from txt
2. Load glyphs YETTP
3. Click on autobuyers
4. Set autobuyer glyps on 10k
5. activate autobuyer
6. do nothing for 30 secs
7. See poopoo

**Expected behavior**
App closes

**Screenshots**

**Savefile**
See txt
[crash report Barrin.txt](https://github.com/antimatter-dimensions/mobile-issues/files/12708570/crash.report.Barrin.txt)

**Additional context**
update is at 50ms. 
Galaxy S22 normal.

**Comment by kajfik** [comment]
Fixed in 2.111.0i35
