### ISSUE TITLE
crash when using teresa music glyps bulk buy

### ISSUE THREAD

**Issue by Barrin84** [antimatter-dimensions/mobile-issues#639]
**Describe the bug**
when you bulk buy teresa music glyps at a faster rate (like every other second) app closes

**To Reproduce**
1. Go to save and load save
2. put in YERRR glyphs
3. Set autobuy 17k
4. automate on glyphs
5. Go tot teresa and buy music glyps a few times (BULK buy)
6. Poopoo --> game closes

**Expected behavior**
app closes when you buy music glyps too fast

**Screenshots**

**Savefile**
see txt
[Uploading crash report Barrin.txt…]()

**Additional context**
Galaxy S22 normal
update settings are on 50ms.

**Comment by kajfik** [comment]
Fixed in 2.111.0i35
