### ISSUE TITLE
sacrifice all glyphs rejected by filtering from Teresa to V and Lateia and beyond

### ISSUE THREAD

**Issue by Barrin84** [antimatter-dimensions/mobile-issues#640]
**Describe the bug**
moment I click on the button of: 'sacrifice all glyphs rejected......'  app closes

**To Reproduce**
1. Go to glyps
2. Click on sacrifice all glyphs rejected by filtering
3. app closes
4. See poopoo

**Expected behavior**
app closes without warning. it loads old save (from seconds before). Like some time didnt pass. 

**Screenshots**

**Savefile**
Dont have save from that time. Need to reproduce with new run.

**Additional context**
Samsung Galaxy S22 normal
update setting 50ms

**Comment by kajfik** [comment]
Fixed in 2.111.0i35
