### ISSUE TITLE
Show the player in the offline summary how much of their ad bonus remains 

### ISSUE THREAD

**Issue by Phoenix51505** [antimatter-dimensions/mobile-issues#644]
**Is your feature request related to a problem? Please describe.**
I find ot slightly interesting that offline progress summary doesn't show how much Ad Bonus is left.

**Describe the solution you'd like**
Appending a "XYZ Seconds/minutes/hours remain." To the end of the ad bonus line in the offline progress report.

**Describe alternatives you've considered**
Just look at the IAP menu and see how long you have left.

**Additional context**
None needed, I think.

**Comment by kajfik** [comment]
no
