### ISSUE TITLE
First Reality Tab misbehavior

### ISSUE THREAD

**Issue by Annyeong-One** [antimatter-dimensions/mobile-issues#645]
**Describe the bug**
When doing the first reality, the bottom tab shows the reality tab while the dimensions tab is actually opened.
Clicking on the perks tab crashes the game.

**To Reproduce**
1. Make sure the bottom navigation is on
2. Reach pre-reality endgame
3. Make a reality
4. "See poopoo"
5. Click on the perks tab to crash the game

**Expected behavior**
Navigation tab should show the correct tab(duh)

**Screenshots**

https://github.com/antimatter-dimensions/mobile-issues/assets/79385636/6a52458a-9190-4656-be82-760be9697ba7

**Savefile**
3 different endgame saves showed the same issues, here's one from the savebank https://pastebin.com/w8w5RYEk

**Additional context**
2.111.0i37

**Comment by GSUI5051** [comment]
That happens to me when I complete 1st reality with e6000+ EP save, but click BH on bottom nav tab.

I get rid of it by clear app data in setting.

**Comment by Annyeong-One** [comment]
Simply restarting the app also fixes I think

**Comment by kajfik** [comment]
Fixed in 2.111.0i38
