### ISSUE TITLE
Last row achievement crash issue on certain languages

### ISSUE THREAD

**Issue by Annyeong-One** [antimatter-dimensions/mobile-issues#646]
**Describe the bug**
Before Pelle, when the language is set to Korean, tapping any of the last row achievements crashes the game.
Not sure is it's only Korean, but other CJK languages did not have this issue so idk

**To Reproduce**
1. Set the language to Korean
2. Tap any of the last row achievements
3. The game crashes

**Expected behavior**
The game should not crash

**Screenshots**
Probably not needed, will upload one if required

**Savefile**
afaik any save before Pelle works (including a new game)

**Additional context**
I did not translate the new achievements yet, maybe that is the issue?
They open as normal just like in the other languages in Pelle

**Comment by GSUI5051** [comment]
That not happens to me in Simplified Chinese. Maybe because I cleared app data to test on issue #645

**Comment by kajfik** [comment]
Fixed in 2.111.0i38
