### ISSUE TITLE
Cheap ID4 and ID5

### ISSUE THREAD

**Issue by TimStanglow** [antimatter-dimensions/mobile-issues#647]
**Describe the bug**
Infinity Diemsions 4 and 5 cost less than expected. (First ones 1e8, afterwards regular price increases.)

**To Reproduce**
Unknown

**Savefile**
https://paste.ee/p/xI1AA

**Additional context**
Newly created game in current version. 
Used SaveEditor to give myself achivment r76 and 143 otherwise nothing unusual.

**Comment by kajfik** [comment]
Fixed in 2.111.0i38
