### ISSUE TITLE
Mysterious Prolong Unlock

### ISSUE THREAD

**Issue by Merlyn02023** [antimatter-dimensions/mobile-issues#648]
**Describe the bug**
Probably After importing a save with a high amount of EP and being inside dilation (possibly an old save), exiting dilation unlocks Existentially Prolong. This issue may occur because the game doesn't recognize there has been more than 1 eternity.

**To Reproduce**
1. Grab the highest ep save from savebank which is pre-reality
2. Unlock reality, and exit dilation
3. See prolong getting unlocked.

**Expected behavior**
  Prolong not getting unlocked.

**Screenshots**
https://cdn.discordapp.com/attachments/554713718282256391/1161654293984710656/IMG_20231011_164858.jpg

**Savefile**
Look at step 1 of trying to reproduce.

**Additional context**
Exiting dilation then unlocking reality and doing an eternity doesn't unlock prolong.

**Comment by kajfik** [comment]
Fixed in 2.111.0i38
