### ISSUE TITLE
Select language at the first opening of the game

### ISSUE THREAD

**Issue by GSUI5051** [antimatter-dimensions/mobile-issues#650]
**Is your feature request related to a problem? Please describe.**
Currently, what happens when opening AD the first time as shown in following video.

(I'm too lazy to change OS language. Sorry for inconvinence.)

https://github.com/antimatter-dimensions/mobile-issues/assets/23095566/241ea1ff-a7ce-4d09-b9d1-ecf31139b17f

Current sequence when open the game for 1st time:

1. Open the game for the **first** time
2. **NOTHING shows**
3. Quit the game ,then open it for **another** time
4. **Popups: Offline progression - Cloud saving - Timeskip prevention (Built-in anti-cheat system) - Language select**

I think players should select desired language when opening the game for the 1st time. 

**Describe the solution you'd like**

Desired sequence when open the game for **first** time:

1. Open the game for the **first** time
2. **Language select interface**
3. **Cloud saving - Timeskip prevention (Built-in anti-cheat system)**

Language select interface shouldn't provided as a drop-down menu, should be **a full-screen list with supported language**, just like when opening _[Exponential Idle](https://play.google.com/store/apps/details?id=com.conicgames.exponentialidle)_ for the **first** time.

**Describe alternatives you've considered**
Just like what happens when opening _[Exponential Idle](https://play.google.com/store/apps/details?id=com.conicgames.exponentialidle)_ for the **first** time.

**Additional context**
N/A

**Comment by kajfik** [comment]
no
