### ISSUE TITLE
Game crash on making a new automator script (sometimes)

### ISSUE THREAD

**Issue by Merlyn02023** [antimatter-dimensions/mobile-issues#651]
**Describe the bug**
Sometimes when making a new automator script the game crashes.

**To Reproduce**
I was not able to consistently reproduce this behavior.
1. Make an automator script
2. Repeat until crash (usually after 1 creation or 2,3)

**Savefile**
Savebank save with 30 Realities.

**Additional context**
The save already had 2 scripts,
Same crash happens after deleting all available scripts (as it attempts to make a new script)
The crash inconsistently happens after 1 or 2 script creations (i was able to create 4 without crashing once)

**Comment by kajfik** [comment]
Fixed in 2.111.0i38
