### ISSUE TITLE
Glyph equip crash bug when changing apps

### ISSUE THREAD

**Issue by Annyeong-One** [antimatter-dimensions/mobile-issues#652]
**Describe the bug**
When clicking on a Glyph, if you open another app through recent apps and come back, offline progress calculations run. Equipping the Glyph crashes the game.

**To Reproduce**
1. Make sure offline progress is on
2. click on a glyph
3. open another app through recent apps screen
4. come back to AD app
5. click equip(glyph)
6. game crashes

**Expected behavior**
Glyph should be equipped, or the Glyph info screen should be closed upon entering offline progress calc.

**Screenshots**
https://github.com/antimatter-dimensions/mobile-issues/assets/79385636/587d1c55-b530-4e32-a7bf-ddc7d1d0a0ec

**Savefile**
https://pastebin.com/2TNfGDaV

**Additional context**
2.111.0i38

**Comment by kajfik** [comment]
Fixed in 2.111.0i39 by closing the glyph info popup when going to another app.
