### ISSUE TITLE
Incorrect Perks when importing a certain web save

### ISSUE THREAD

**Issue by Merlyn02023** [antimatter-dimensions/mobile-issues#653]
**Describe the bug**
Importing this certain web save slightly messed up the perks, in the web save TTS is purchased but upon importing the save to mobile TTF is purchased instead

**To Reproduce**
1. Go to [Savebank](https://buck4437.github.io/save-bank/)
2. Grab the save with 33 realities and import it
3. Notice the weirdness of TTF being purchased instead of TTS

**Expected behavior**
Perks being the same as the web save on android

**Screenshots**

![image](https://github.com/antimatter-dimensions/mobile-issues/assets/147642455/bd437588-2e54-4931-bb4b-687a5c1ed85c)
   ***On Web***
   
   
![image](https://github.com/antimatter-dimensions/mobile-issues/assets/147642455/36aef664-da5a-4527-bcb3-39a95f0fa92d)
***On Android***

**Savefile**
Look at Step 1,2

**Additional context**
I didn't notice this happening with another save
edit: After messing around a bit (using console on web to lock TTS and unlock TTF then importing it to mobile) i noticed that this time TTS is purchased and TTF is not

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
