### ISSUE TITLE
IP colouring isn't right, right after Reality

### ISSUE THREAD

**Issue by KirinNijinski** [antimatter-dimensions/mobile-issues#654]
**Describe the bug**
Right after realitying (R1 to at least R5), IP colouring is red while never having infinityied. 

**To Reproduce**
1. Reality without infinity autobuyer.
2. See the red colouring on IP.

**Expected behavior**
Since in this reality there wasn't any previous infinity, IP should be green.

**Screenshot**
See screenshot 
![Screenshot_2023-10-14-00-02-16-55_a1dfedc045cf59f718484c5373a1c563](https://github.com/antimatter-dimensions/mobile-issues/assets/126246458/e11df85c-bbcb-4271-9e1c-44eb5de7d692)

**Additional context**
I would guess this is due to the last IP on infinity being the one from the previous reality. And so really high. I think resetting that variable to 0 on reality would do the trick ?

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
