### ISSUE TITLE
Importing embedded script does not import the constants too.

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#655]
**Describe the bug**
Title

**To Reproduce**
1. Have automator
2. Import a script that is embedded with constants (I used ninja's PreECR)
3. Open the constant menu in the automator tab
4. Sadage

**Expected behavior**
Constant(s) should be imported, but it instead creates a couple empty constant slots.

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
