### ISSUE TITLE
Constants doesn't work in automator

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#656]
**Describe the bug**
Title

**To Reproduce**
1. Have automator
2. Create constants
3. Run a line that use a constant (i.e. : Studies purchase TREE
4. The automator will "run" the command, going to the next line, but your TS tree will be empty.

**Expected behavior**
It should purchase the studies in the constant

**Savefile**
[fRj9Yxnz.txt](https://github.com/antimatter-dimensions/mobile-issues/files/12899812/fRj9Yxnz.txt)

**Comment by BsonHK** [comment]
It seems like this bug only happens when you shorten the ts in the constant. For example, 11-62. It works fine if it's 11,21,22... 62.

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
