### ISSUE TITLE
Automator doesn't highlight currently running line.

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#657]
**Is your feature request related to a problem? Please describe.**
The automator does not highlight which line it is running, making it confusing to figure out where it currently is.

**Describe the solution you'd like**
Highlight the line of code it is currently running.
![Automator](https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/1e9972fe-ed5d-490b-ad8f-ca6ca53018ba)

**Comment by kajfik** [comment]
Added in 2.111.0i50
