### ISSUE TITLE
Blackhole autopause pause at 5 ms instead of 5 s.

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#658]
**Describe the bug**
Title

**To Reproduce**
1. Have blackhole ***in game*** (not irl)
2. Turn on autopause

**Expected behavior**
It should have paused 5 secs before activation, not 5 ms

**Screenshots**
![BH](https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/ff1a6ff8-450b-49d0-9c77-61b93846148c)

**Additional context**
Blackhole runs slower right after unpausing it, this bug loses precious blackhole run time.

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
