### ISSUE TITLE
Tap Dim Boost label to show the actual amount 

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#659]
**Is your feature request related to a problem? Please describe.**
Tap Dim Boost label to show the actual amount, like we can do so with AG.

**Additional context**
![Screenshot_2023-10-14-17-24-14-49_a1dfedc045cf59f718484c5373a1c563~3](https://github.com/antimatter-dimensions/mobile-issues/assets/56225774/63252cee-93dd-48b6-b3e6-ebb24706cd87)

**Comment by kajfik** [comment]
Added in 3.8.4i1
