### ISSUE TITLE
Game frozen after importing a certain save.

### ISSUE THREAD

**Issue by Merlyn02023** [antimatter-dimensions/mobile-issues#661]
**Describe the bug**
autobuyers and dimensions are frozen after importing certain save from savebank which has e59 RM

**To Reproduce**
1. Go to [Savebank](https://buck4437.github.io/save-bank/)
2. Grab the save with e59 RM and import it
3. Observe

**Expected behavior**
Game functioning normally and not freezing

**Savefile**
Step 1 and 2 of reproducing

**Additional context**
After importing this save and loading other saves they also freeze until restarting the game, but this save doesn't fix itself after restarting

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
The autobuyers and dimensions are supposed to not work with real time storing enabled, but other saves should not freeze anymore.
