### ISSUE TITLE
bug when losing 1st bar in galaxy automator. (vacuum hollow void)

### ISSUE THREAD

**Issue by Barrin84** [antimatter-dimensions/mobile-issues#663]
**Describe the bug**
the moment I was done losing bar 1 the game crashed. 

**To Reproduce**
1. Go to galaxy autobuyer. 
2. Click on the upgrades till it says: no more space, you need to sacrfice hollow,void,vacuum
3. Wait till the bar is empty
4. See poopoo ---> crash

**Expected behavior**
moment the bar is empty, it crashed the app

**Screenshots**

**Savefile**
couldnt save and cant login, as it crashes the moment I get a single tick. 

**Additional context**

**Comment by Annyeong-One** [comment]
I was able to reproduce the bug with the save from savebank.
https://pastebin.com/CmeQzJRz is the save right before sacrifice.
Doing so will **_brick the save AND the whole app_**, make sure to export any important save before trying

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
