### ISSUE TITLE
H2p and about page unresponsive when inside Nameless reality

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#664]
**Describe the bug**
Title

**To Reproduce**
1. Enter Nameless reality
2. Click h2p and about page
3. Page does not load
4. Click the sub tab button
5. Page loads

**Expected behavior**
Clicking the tab should load the page

**Screenshots**
https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/7c151e84-f80d-40d5-8991-e75ccbfc82b2

**Additional context**
I hid those pages, maybe if they are unhidden they would work as normal.

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
