### ISSUE TITLE
Post-reality IP multiplier cost scaling

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#665]
**Is your feature request related to a problem? Please describe.**
Web-mobile parity.

**Describe the solution you'd like**
Mention post e3e6 IP multiplier cost scaling, and capping at e6e6 IP.

**Additional context**
This screenshot is from web.
![image](https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/9892d46e-0ab8-488e-9aa6-50a1ff6b91e7)

**Comment by kajfik** [comment]
Added in 2.111.0i40
