### ISSUE TITLE
Automator duplicate constant exception bug

### ISSUE THREAD

**Issue by Annyeong-One** [antimatter-dimensions/mobile-issues#668]
**Describe the bug**
It is possible to 'kind of' make 2 constants with the same name.
Trying to delete one crashes the game, and restarting or exporting and importing the game deletes one.

**To Reproduce**
1. Make 2 automator constants with the same name
2. Try to delete one to crash the game

**Expected behavior**
The exception window should correctly show

**Screenshots**
![pic](https://github.com/antimatter-dimensions/mobile-issues/assets/79385636/7a2dc834-0353-422b-8351-08598a841bc5)

**Savefile**
Saving such a save deletes one of the constants.

**Additional context**
0i39

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
