### ISSUE TITLE
Some automator script does not read the constant correctly

### ISSUE THREAD

**Issue by Annyeong-One** [antimatter-dimensions/mobile-issues#669]
**Describe the bug**
As the title. When using the automator with constants, some of the constants will not will be correctly matched and the script will not run.
Savefile uses Ninja Cel4 script at https://paste.ee/p/k7ifa. Deleting and redefining constants will not work.

**To Reproduce**
1. I have no idea how to make a such script, nor the condition of such a script.

**Expected behavior**
The automator should run.

**Screenshots**
https://github.com/antimatter-dimensions/mobile-issues/assets/79385636/a0f5f700-6ee0-4791-9417-eb5bd2dcdd99

**Savefile**
https://pastebin.com/iRZ3Ha02

**Additional context**
0i39
- renaming the constants fixes the bug, so the bug is probably associated with importing a script with constants
- renaming the constants, but just capitalization or the reverse somehow doesn't work

**Comment by Annyeong-One** [comment]
- I think the bug has something to do with the constant name length, found out that renaming the constants with anything longer than a single character does not work
- Just making a new script with 2 constants named 'aa' and 'bb' works though, so the length is not the only issue

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
