### ISSUE TITLE
TS 131 is still active after TT reset from exiting a EC

### ISSUE THREAD

**Issue by HifuminOwO** [antimatter-dimensions/mobile-issues#67]
The effect of TS 131 which disables auto replicanti galaxies, the text of it still shows up after the reset of TT after exiting a eternity challenge

*EDIT* 
It happens even if you only have TS 131 and respecc TT

**To Reproduce**
1. Enter a eternity challenge with TS 131 ( preferably EC1x4
2. When finishing the challenge stay on the replicanti tab
3. Do the required 2400 IP crunch
4. And then your TT will reset and the text of "disabled" will be still visible

**Expected behavior**
The text should disappear

**Screenshots**
![Screenshot_2019-09-10-13-43-50-662_kajfosz antimatterdimensions](https://user-images.githubusercontent.com/55025752/64608115-a1a44100-d3d2-11e9-8b43-c85d50c5ce60.png)

SAVE :

https://pastebin.com/Dm2pJQjc

**Comment by kajfik** [comment]
Fixed in 2.9.4
