### ISSUE TITLE
Update automator script highlight upon editing constants

### ISSUE THREAD

**Issue by Annyeong-One** [antimatter-dimensions/mobile-issues#670]
**Is your feature request related to a problem? Please describe.**
When writing the script with some constants before actually creating them, the row with the constant will not get highlighted until making an edit to the script. This makes it a little confusing to see if/where the script is wrong.
This includes when running the script; the script will run with the line unhighlighted.

**Describe the solution you'd like**
Also update the script highlighting upon creating, editing, or deleting a variable.

**Describe alternatives you've considered**
- Update them upon running the script
- Make a highlight update button or smth?

**Additional context**

**Comment by kajfik** [comment]
Improved in 2.111.0i40
