### ISSUE TITLE
Cel 3 symbol in glyph visual customisation is garbled

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#671]
**Describe the bug**
Cel 3 symbol in the glyph visual customisation is garbled.

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Go to glyph visual options 
2. See error

**Expected behavior**
Not garbled.

**Screenshots**
https://discord.com/channels/351476683016241162/1075464056544182339/1163445189533237369

**Comment by kajfik** [comment]
Fixed in 2.111.0i40
