### ISSUE TITLE
Automator crash

### ISSUE THREAD

**Issue by KirinNijinski** [antimatter-dimensions/mobile-issues#673]
**Describe the bug**
The game crashes upon modifying code in the automator 

**To Reproduce**
1. Go to the tomato tab, in either one of the two scripts
2. Go to the 28th line or any other one after it
3. Modify this line : add or delete a character 
4. The line turns white (unknown command)
5. The game crashes and force close

**Expected behavior**
Not crashing

**Screenshots**
Uhhh I do not know how to put a video on this, so I can send it to you through discord ?

**Savefile**
https://paste.ee/p/6GcCc

**Additional context**
Since this could be a phone issue : One plus nord CE 2. I'm using Gboard as keyboard

**Comment by KirinNijinski** [comment]
Oh yes. The game also crashes with other scripts. I tried for exemple the "jesse pinkman" from the breaking bad compilation.

**Comment by KirinNijinski** [comment]
Alright this is the video describing what's happening https://media.discordapp.net/attachments/554713718282256391/1163920228095361094/Record_2023-10-17-21-21-26_a1dfedc045cf59f718484c5373a1c563.mp4?ex=6541542e&is=652edf2e&hm=7054a2f92d4c86faf6dd1ec4768c9c8969527a6e4f7b3a8b5a9f40dc2ecbf82a&

**Comment by kajfik** [comment]
this has probably been fixed, if it happens again feel free to reopen the issue
