### ISSUE TITLE
Automator Crash most likely when it triggered command tip box.

### ISSUE THREAD

**Issue by Sxy6214** [antimatter-dimensions/mobile-issues#674]
**Describe the bug**
Automator would cause an almost guarantee game crash when the text edit could trigger command tip box AND this script was the one being automated before. Editing a total new script would have much less possibility to trigger, but it still may happen.
Related spesific bug, see [#673](https://github.com/antimatter-dimensions/mobile-issues/issues/673) and [#662](https://github.com/antimatter-dimensions/mobile-issues/issues/662) .

**To Reproduce**
1. Load an automator script then run it. Any avaliable script could count, using [kajfik's early reality script](https://paste.ee/p/cAavo) as example.
2. Pause/halt script running or just begin edit (which game would halt script running as expected)
3. Make an edit that could trigger command tip box. For example deleting word "eternity" last y and cursor at the end of "eternit"

**Expected behavior**
The command tip box appear, showing options of "eternity" and "eternities".

**True behavior**
Game crashes.

**Savefile**
paste.ee/p/glaXz

**Additional context**
This is leading to a very uncomfort editing experience, making editing automator on phone almost impossible.
Players could try to avoid triggering this bug by using some text edit trick, like editing right at the beginning of another word, with space typed last, or type two spaces when using space so if want add commands afterwards player could add it in the middle of two spaces with out the risk of cursor being at the end of some command triggering command tip box.

**Comment by kajfik** [comment]
this has probably been fixed, if it happens again feel free to reopen the issue
