### ISSUE TITLE
Black screen on tab switching

### ISSUE THREAD

**Issue by FredrIQ** [antimatter-dimensions/mobile-issues#675]
**Describe the bug**
When I "tab" out (switch to a different app) and then back, the game shows a black screen. The "This happened while you were away" dialog shows as normal.

**To Reproduce**
1. Start AD
2. Activate the app switcher (you do not need to actually switch to a different app)
3. Resume AD
4. Observe the black screen
5. Deattaching the keyboard cover which causes a change in screen resolution will also cause the same problem even if you remain within AD during the entire time

**Expected behavior**
No black screen should display

**Screenshots**
![Screenshot_20231018-150032_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/5430027/5d4beaca-3c73-400f-80d8-6f21070296ec)

**Savefile**
n/a

**Additional context**
Phone: Samsung Galaxy S7 Edge w/keyboard cover (deattaching it makes no difference, just mentioning this to explain the odd screen resolution in the screenshot)
OS: Android 8.0.0
Samsung Experience Version: 9.0 (figured I'd mention this in case the Samsung-specific UI is causing problems)

**Comment by JohanniklasLp** [comment]
I have the same issue. (Different Phone, see below)
You can actually still interact with the UI, and popups are still shown as normal, the UI is just invisible. It gets fixed when you fully close and reopen the app

This does not happen when messing with the night mode and orientation settings (those are the two I tested that change the look of the game), it seems to be limited to actually minimizing the game

The issue happened both on my pre cel 1 save and on a fresh save, and even after reinstalling.

https://github.com/antimatter-dimensions/mobile-issues/assets/57828910/d604fc66-607b-4902-bf68-1816d2e42f6a

**Additional context**
Phone: Samsung Galaxy S9+
OS: Android 9.0.0

**Comment by Jeedorah** [comment]
I have the same issue since the last time i have opened the app. Didn't encounter it 2 months ago but now with reality i does not work anymore. Also using Android but different Phone model.

**Comment by FredrIQ** [comment]
> I have the same issue since the last time i have opened the app. Didn't encounter it 2 months ago but now with reality i does not work anymore. Also using Android but different Phone model.

The bug report was done on the Reality version when in testing, so presumably a regression early on during the work on that update. Made the app basically unusable making me unable to test it properly but oh well.
