### ISSUE TITLE
Reality Animation 

### ISSUE THREAD

**Issue by Gfadezero** [antimatter-dimensions/mobile-issues#677]
**Describe the bug**
Pressing the window change button on an android device during the animation for a reality will cause it to pause the animation and remain paused even when changing windows again, it also prevents the reality from occurring. 

**To Reproduce**
1. Reality
2. go to a different window on your phone, I was able to go to my home page and google chrome both producing the effect
3. Reopen app (this appears to be any amount of time waited ~3 min while writing to test between tabing out during animation and its pause, the pop up window for offline progress still appears and does not resume the animation)
4. Animation is paused but screen is still interactable, and the reality press fails 

**Expected behavior**
The animation to be skipped//still play out and the reality to be completed. 

**Screenshots**

https://github.com/antimatter-dimensions/mobile-issues/assets/63206238/fd05df9a-3d7f-4fd8-9762-5634d41f636e

**Comment by kajfik** [comment]
Fixed in 2.111.0i43
