### ISSUE TITLE
Double/Triple Sacrifice.

### ISSUE THREAD

**Issue by GuiMora12** [antimatter-dimensions/mobile-issues#679]
**Describe the bug**
Multiple sacrifices with a single glyph.

**To Reproduce**
Enter the glyphs page and quickly click onto any glyph. Its interface opens multiple times, and clicking "sacrifice" will sacrifice the glyph, but won't close all dialogues, allowing you to sacrifice many times.

**Expected behavior**
You usually don't sacrifice glyphs more than once.

**Screenshots**
Video demonstration in the fishy discord channel. I don't know how to send it here.

**Comment by Hirame1** [comment]
You can copy a link to the message by long tapping then select in the popup menu.

https://discord.com/channels/351476683016241162/554713718282256391/1164990103337312367

**Comment by kajfik** [comment]
Fixed in 2.111.0i43
