### ISSUE TITLE
IAP 6 hour offline progress in EC5x2 to crunch not working

### ISSUE THREAD

**Issue by HifuminOwO** [antimatter-dimensions/mobile-issues#68]
I used IAP 6 hour offline progress in EC5x2 as a result of when i passed the requirement and crunched it didn't gave me the IP, it got stuck at 1110 IP even when i crunched as well as the infinity upgrade

**To Reproduce**
1. Enter EC5x2 ( save below )
2. Go until 1000-1100 IP
3. Then use IAP 6 hour offline progress until you surpass the requirement of 1150
4. When you crunch it's not giving the IP

**Expected behavior**
When you crunch to give the IP 

**Screenshots**
![Screenshot_2019-09-10-14-41-10-154_kajfosz antimatterdimensions](https://user-images.githubusercontent.com/55025752/64611344-e5e70f80-d3d9-11e9-93ae-ce6c626b229e.png)
![Screenshot_2019-09-10-14-41-06-642_kajfosz antimatterdimensions](https://user-images.githubusercontent.com/55025752/64611352-e8e20000-d3d9-11e9-89a3-6586c27f2b36.png)
![Screenshot_2019-09-10-14-49-28-626_kajfosz antimatterdimensions](https://user-images.githubusercontent.com/55025752/64611479-3bbbb780-d3da-11e9-9290-daf0bb23c61c.png)

**Savefile**
https://pastebin.com/Fvv281ip

**Comment by kajfik** [comment]
Not a bug, the crunch button shows e1045, not e1145 IP.

**Comment by HifuminOwO** [comment]
Yes it is my fault, i got confused.
