### ISSUE TITLE
BH pause / Unpause button disappeared in cel 6

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#680]
**Describe the bug**
Cel 6 doesn't disable BH, but the BH Pause/Unpause button is disappeared in it.

**To Reproduce**
1. Start cel 6's reality.
2. See poopoo

https://discord.com/channels/351476683016241162/1075464056544182339/1164579823050575923

**Comment by kajfik** [comment]
Fixed in 2.111.0i43
