### ISSUE TITLE
Effarig Glyph Bonus Positioning

### ISSUE THREAD

**Issue by TimStanglow** [antimatter-dimensions/mobile-issues#681]
**Is your feature request related to a problem? Please describe.**
The effarig glyph's bonuses 1 and 2 (RM and glyph instablitly) are in switched/reversed positions compared to web/steam.
Is going to be confusing for players looking to for help from discord pinned messages for example.

**Describe the solution you'd like**
Switch them back.

**Comment by kajfik** [comment]
Fixed in 2.111.0i43
