### ISSUE TITLE
bottom button doesn't stay highlighted on checking notifs

### ISSUE THREAD

**Issue by Calmcat5** [antimatter-dimensions/mobile-issues#683]
**Description**
Sticky bottom buttons do not visually display as pressed when checking notifications through Android.

1. Stick any bottom button
2. Note greyed-out appearance
3. Swipe down from top of screen to see notifications and pinned settings
4. Exit notification menu back into the game by swiping up
5. Note how bottom button still behaves as pressed but does not appear greyed-out

**Comment by Calmcat5** [comment]
video for reference
https://github.com/antimatter-dimensions/mobile-issues/assets/94936969/ebb31a2a-c7b8-44a9-a2eb-0279c1735646

**Comment by kajfik** [comment]
Fixed in 2.111.0i45
