### ISSUE TITLE
Glyph Preset

### ISSUE THREAD

**Issue by AshTheDinosaur** [antimatter-dimensions/mobile-issues#684]
**Describe the bug**
When deleteing an old Glyph Preset you become unable to save a new preset

**To Reproduce**
1. Delete a Glyph Preset
2. Try to save a new preset
3. Maybe Reality in between
(relog fixes it)

**Expected behavior**
Be able to save the new preset imediatly

**Screenshots**
![Glyph Preset Bug](https://github.com/antimatter-dimensions/mobile-issues/assets/147666002/4bebe281-f698-43f9-9175-03c0cc535401)

**Savefile**
[Savefile.](https://paste.ee/p/oqwbw)

**Additional context**

**Comment by kajfik** [comment]
Fixed in 2.111.0i45
