### ISSUE TITLE
Buy all dilation upgrades doesn't buy the ones granted from pelle rift

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#685]
**Describe the bug**
See title or recording in discord (link)

**To Reproduce**
1. Load save
2. Hit buy all upgrades

3. See poopoo. It doesn't buy all upgrades

**Expected behavior**
Button buys all upgrades

**Screen recording**
https://discord.com/channels/351476683016241162/554713718282256391/1168547192991121550

**Savefile**
https://paste.ee/p/KPkUM

**Comment by L4R5W** [comment]
**Additional content**
Maybe disable option to buy 1xTP upgrade when the rift is capped (×712, I think around 45 bought rebuyables)

**Comment by kajfik** [comment]
Fixed in 2.111.0i45
