### ISSUE TITLE
Font setting for H2P Singularity entry should be improved 

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#687]
**Describe the bug**
Symbols used in the H2P Singularity entry don't match with the actual symbols in the Cel 6 tab.

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Go to H2P
2. Open Singularity entry
3. See symbols at bottom 
4. Relax and see error

**Expected behavior**
Symbols are same on H2P and Cel 6 tab.

**Screenshots**
https://discord.com/channels/351476683016241162/1075464056544182339/1179393128587862027

**Comment by kajfik** [comment]
Fixed in 3.8.3i1
