### ISSUE TITLE
V unlock visual bug

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#688]
**Describe the bug**
After completing the requirement to unlock V's achievements, the hexagons won't appear.

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Unlock V
2. Meet the requirements
3. Unlock V's achievement
4. Bug
5. Switch tab
6. Bug fix

**Expected behavior**
The hexagons should appear when you unlock it
https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/f1e56d24-a66b-4433-b761-25771b97aff2

**Comment by kajfik** [comment]
Fixed in 2.111.0i52
