### ISSUE TITLE
Ra's upgrade for mem gen are mixed up.

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#689]
**Describe the bug**
Leveling up recollection incraese mem chunk visually, while fragmentation does nothing.

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Upgrade recollection
2. Visual bug for mem chunk multi.

**Expected behavior**
Upgrading recollection affects mem gen only, and fragmentationaffects mem chunk only.

**Screenshots**

https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/fcd3b5bc-770f-4927-af43-abc056f9f3d7

**Comment by kajfik** [comment]
Fixed in 2.111.0i50
