### ISSUE TITLE
Momentum is different from web.

### ISSUE THREAD

**Issue by BsonHK** [antimatter-dimensions/mobile-issues#690]
**Describe the issue**
The spped you gain momentum is different from wwb.

**Describe the solution you'd like**
Fix the parity.

**Additional context**
Web incraesed momentum gain a few updates ago.
![Screenshot_20231207_134424_Antimatter Dimensions](https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/ad5c4db8-4a18-428a-b1ad-a2658236dfd8)
![Screenshot_20231207_134447_Chrome](https://github.com/antimatter-dimensions/mobile-issues/assets/147670807/df2c40a7-1669-49e1-bfdb-ad71e82c89f6)

**Comment by kajfik** [comment]
Fixed in 2.111.0i50
