### ISSUE TITLE
Move study tab up to show full drop-down menu on study presets

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#702]
Poopoo:
![Screenshot_20240331-194211_a1dfedc045cf59f718484c5373a1c563.jpg](https://github.com/antimatter-dimensions/mobile-issues/assets/66326188/6104d4cd-ac5b-474a-bdef-a9021cb601de)

Perhaps add glyph-tooltip-like-code so the tab moves a little to show the full drop-down menu. (`clear` is also cut off at the bottom)

**Comment by kajfik** [comment]
Implemented in 3.8.4i1
