### ISSUE TITLE
Notifications get in the way of bottom buttons

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#703]
**Is your feature request related to a problem? Please describe.**
![Screenshot_20240402-123912_a1dfedc045cf59f718484c5373a1c563.jpg](https://github.com/antimatter-dimensions/mobile-issues/assets/66326188/1a498be5-ced6-4070-af49-b2b9dea3adec)

**Describe the solution you'd like**
![Screenshot_20240402-124039_a1dfedc045cf59f718484c5373a1c563.jpg](https://github.com/antimatter-dimensions/mobile-issues/assets/66326188/08ec050f-4086-409a-99c3-1652d494569d)

**Describe alternatives you've considered**
Move notifications to top bar, alternatively raise bottom buttons slightly (maybe just for when a notifications pops up? Unsure if that would look and feel any good.)

**Additional context**
Reality is out :blobblewobble:

**Comment by kajfik** [comment]
Fixed at some point
