### ISSUE TITLE
Add challenge display in cel 7

### ISSUE THREAD

**Issue by Hirame1** [antimatter-dimensions/mobile-issues#707]
**Is your feature request related to a problem? Please describe.**
Currently there's no challenge display in cel 7.

**Describe the solution you'd like**
Add the one like the web version.

**Additional context**
![Screenshot_2024-04-07-12-32-48-89_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://github.com/antimatter-dimensions/mobile-issues/assets/56225774/ec2e8bff-27ef-47b1-9f86-52d8a90c67c8)

**Comment by kajfik** [comment]
Added in 3.4.1i1
