### ISSUE TITLE
TP color is much eww

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#711]
**Is your feature request related to a problem? Please describe.**
See title

**Describe the solution you'd like**
Darken it, why is it even a different colour now??

**Describe alternatives you've considered**
Make it same colour as background so only the TP animation reveals the amount you have. Good luck when little amount of TP lol

**Additional context**
Here, have a :blobheart: :
:blobheart:

**Comment by kajfik** [comment]
Fixed in 3.2.0i1
