### ISSUE TITLE
Running tomato script pauses when reviewing the running script

### ISSUE THREAD

**Issue by L4R5W** [antimatter-dimensions/mobile-issues#712]
**Describe the bug**
If you run script A, then switch to view a different script B and switch back to view the running script A, tomato pauses.

**To Reproduce**
1. Run a script
2. Select a different script to view (don't need any edits)
3. Select the running script
4. See poopoo (tomato stops)

**Expected behavior**
Tomato resumes the script and doesn't stop

**Savefile**
https://paste.ee/p/aI2XK

**Additional context**
Just running script A and then selecting script A to ""switch"" to view script A also breaks tomato the same way.

**Comment by kajfik** [comment]
Fixed in 3.3.3i1
