### ISSUE TITLE
Importing a web save to mobile will set the autocrunch to "crunch at X IP" even if it was set differently in the save

### ISSUE THREAD

**Issue by rukimix** [antimatter-dimensions/mobile-issues#79]
If you import a web save to mobile it will change the Big crunch autobuyer to "Big Crunch at X IP" even if it was set differently in the save. If you open the same save on web it will work properly.

To reproduce simply "export to web" on options and import it back, the big crunch autobuyer preset will change.

**Comment by kajfik** [comment]
Fixed in 2.10.9
